// Read-only Git review, separate from unsaved editor buffers and runtime evidence.
export function initChangeReview({el,button,body,tree,editorHost,toolbar,request,report,openFile,onState,discussPatch}) {
  let open=false,busy=false,queued=false,revision=0,selected=null;
  const list=el('nav',undefined,'change-tree');list.id='change-tree';list.hidden=true;
  const content=el('div',undefined,'change-diff');content.id='change-diff';content.hidden=true;
  body.append(list,content);
  const toggle=button('Changes','editor-changes',()=>open?hide():show());toggle.setAttribute('aria-pressed','false');toolbar.append(toggle);
  function hide(){open=false;revision++;tree.hidden=false;editorHost.hidden=false;list.hidden=true;content.hidden=true;toggle.setAttribute('aria-pressed','false');onState();}
  async function show(){content.replaceChildren(el('p','Reading current changes…','review-note'));open=true;tree.hidden=true;editorHost.hidden=true;list.hidden=false;content.hidden=false;toggle.setAttribute('aria-pressed','true');onState();await refresh();}
  async function refresh(){if(busy){queued=true;return;}queued=false;busy=true;const token=++revision;report('editor','Reading changes saved on disk…');try{const data=await request('changes');if(token!==revision)return;list.replaceChildren(button('↻ Refresh changes','changes-refresh',refresh));content.replaceChildren(el('p','Choose a changed file. Unsaved editor drafts are not included.','review-note'));for(const f of data.entries){const b=button(`${f.index}${f.working}  ${f.path}`,'',()=>diff(f));b.dataset.changePath=f.path;b.title=f.path;list.append(b);}if(!data.entries.length)content.replaceChildren(el('p','No changes reported by Git. Save your editor drafts to include them here.','review-note'));if(data.truncated)list.append(el('p','First 1,000 changed files.','review-note'));report('editor',`${data.entries.length}${data.truncated?'+':''} changed files · Saved disk state · No staging or commits`);if(selected&&data.entries.some(f=>f.path===selected.path))await diff(selected);}catch(e){if(token===revision){content.replaceChildren(el('p',String(e),'review-note'));report('editor',e);}}finally{busy=false;if(queued&&open)refresh();}}
  async function diff(f){selected=f;const token=++revision;content.replaceChildren(el('p','Loading '+f.path+'…','review-note'));try{const d=await request('diff',{path:f.path});if(token!==revision||!open)return;content.replaceChildren();const head=el('div',undefined,'review-heading');head.append(el('strong',d.path),button('Open in Editor','changes-open-file',()=>{hide();openFile(d.path);}));head.append(button('Discuss changes with bot','changes-discuss',()=>discussPatch(d)));content.append(head);
      function section(title,text,newFile=false){if(text===null||text===undefined||(!text&&!newFile))return;content.append(el('h2',title));if(!text){content.append(el('p','Empty file','review-note'));return;}const code=el('pre');const lines=text.split('\n');for(const line of lines.slice(0,5000)){const cls=newFile?'diff-added':line.startsWith('@@')?'diff-hunk':line.startsWith('+')?'diff-added':line.startsWith('-')?'diff-removed':'';code.append(el('span',line.slice(0,4000)+'\n',cls));}if(lines.length>5000||lines.some(l=>l.length>4000))content.append(el('p','Display shortened for a large change. Inspect the full patch in your Git tools.','review-note'));content.append(code);}
      section('Working tree · compared with index',d.working);section('Staged · compared with HEAD',d.staged);section('Untracked file · not staged',d.untracked,true);if(!d.working&&!d.staged&&d.untracked===null)content.append(el('p','No text diff reported. The file may have changed since the list was refreshed.','review-note'));report('editor',d.path+' · Git diff snapshot · Refresh to check for newer edits');
    }catch(e){if(token===revision){content.replaceChildren(el('p',String(e),'review-note'));report('editor',e);}}}
  return {hide,show,showPath(path){selected={path};return show();},reset(){hide();selected=null;list.replaceChildren();content.replaceChildren();},get open(){return open;}};
}
