import {reviewProposalSet} from './file-proposal-set-review.js';
import {checkProposalSet} from './file-proposal-set.js';
import {publishTaskEditor,canOpenTaskEditor} from './task-editor.js';
import {relatedFileSelection} from './related-files.js';
import {taskFileAttachment} from './task-file-context.js';
import {reviewFileProposal} from './file-proposal-review.js';
import {sessionLinks} from './linked-sessions.js';
import {createWorkbenchRecovery,recoveryFile,patchAttachment} from './workbench-recovery.js';
import {initChangeReview} from './change-review.js';
import {codeEditor} from './vendor/code-editor.js';
import {createBotRoster} from './bot-roster.js';
import {navigate} from './app-shell.js';
import {heldProjection,runtimeWorld,waitForBot} from './runtime-bots.js';
// Device-local work surfaces; runtime observations stay bound to their worker.
export function initDevelopment({invoke,apply,recordAttempt,recordSet,current}) {
  const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
  const button=(text,id,fn)=>{const b=el('button',text);b.type='button';b.id=id;b.onclick=fn;return b;};
  const recoveryStore=createWorkbenchRecovery(localStorage),initialRecovery=recoveryStore.snapshot(),recoveryBars={};
  let recoveryTimer=0,recoveryProblem=recoveryStore.error||'',projectReady=false,browserReady=false,shellReady=false,recovering=false;
  const canvas=document.getElementById('workspace-canvas'),pages={},bars={},statuses={},bodies={},choosers=[];
  let active='',root=null,generation=0,folder='',busy=false,file=null,shell=null,browser=null,polling=false,worker=null,workerWorld=null;
  let shellSignature='',workerSignature='',browserSignature='',lastBrowserPoll=0,lastInventoryPoll=-Infinity,lastSurface='',surfaceTail=Promise.resolve(),layoutFrame=0,files=new Map(),shells=new Map(),browsers=new Map();
  let activeTask=null;
  const surfaceSession=crypto.randomUUID(),links=sessionLinks(invoke);
  const request=(operation,args={})=>invoke('development_request',{request:{operation,...(operation==='status'?{}:{generation}),...args}});
  const report=(id,e)=>statuses[id].textContent=String(e);
  for(const id of ['editor','terminal','browser']){
    const page=el('section',undefined,'app-screen development-screen');page.dataset.screen=id;page.dataset.source='local-development';page.hidden=true;
    const tabs=el('div',undefined,'workbench-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label',id+' tabs');
    const toolbar=el('div',undefined,'workbench-toolbar');
    const picker=button('Open repository…','development-choose-'+id,choose);choosers.push(picker);
    const repo=el('span','No repository selected','workbench-root');toolbar.append(picker,repo);
    const bot=el('select');bot.setAttribute('aria-label','Bot for '+id);bot.className='surface-bot';
    bot.onfocus=()=>{const selected=bot.value;bot.replaceChildren();for(const b of createBotRoster(localStorage).list()){const o=el('option',b.name);o.value=b.id;bot.append(o);}if([...bot.options].some(o=>o.value===selected))bot.value=selected;};bot.onfocus();
    toolbar.append(bot,button('Discuss with bot',id+'-discuss',()=>discuss(id,bot.value)));if(id==='editor')toolbar.append(button('Share related files', 'editor-share-files',()=>shareRelatedFiles(bot.value)));
    const body=el('div',undefined,'workbench-body'),status=el('div','','development-status');status.id=id+'-status';status.setAttribute('role','status');
    const recoveryBar=el('div',undefined,'workbench-recovery');recoveryBar.setAttribute('role','status');recoveryBars[id]=recoveryBar;page.append(tabs,toolbar,recoveryBar,body,status);canvas.append(page);pages[id]=page;bars[id]=tabs;bodies[id]=body;statuses[id]=status;
  }
  const tree=el('nav',undefined,'development-tree');tree.id='editor-tree';tree.setAttribute('aria-label','Repository files');
  const treebar=el('div',undefined,'tree-toolbar');treebar.append(button('↑','editor-up',()=>list(folder.split('/').slice(0,-1).join('/'))),button('↻','editor-refresh',()=>list(folder)),button('+ File','editor-new',()=>{if(!root||busy)return;const path=prompt('New file path, relative to this repository');if(path)addFile(path,null);}));
  const entries=el('div');tree.append(treebar,entries);const editorHost=el('div');editorHost.id='editor-content';bodies.editor.classList.add('editor-body');bodies.editor.append(tree,editorHost);
  const editor=codeEditor(editorHost,text=>{if(file){file.draft=text;file.state=editor.current();paintFiles();}},saveFile);editor.readonly(true);
  pages.editor.querySelector('.workbench-toolbar').append(button('Reload','editor-reload',reloadFile),button('Save','editor-save',saveFile));
  let stagedSet=null,pendingSet=null;
  const setBar=el('div',undefined,'workbench-recovery');setBar.id='editor-change-set';setBar.hidden=true;setBar.style.flexWrap='wrap';
  function paintSet(){
    setBar.replaceChildren();setBar.hidden=!stagedSet&&!pendingSet;
    if(pendingSet){
      setBar.append(el('span','Interrupted file application: '+pendingSet.paths.join(', ')+'. Finish applying or restore the originals. Other edits are preserved.'));
      for(const [label,restore,id] of [['Finish applying',false,'editor-set-finish'],['Restore originals',true,'editor-set-restore']]){const b=button(label,id,()=>recoverSet(restore));b.disabled=busy;setBar.append(b);}
    }else if(stagedSet){const b=button('Apply staged change set','editor-set-apply',applyStagedSet);b.disabled=busy;setBar.append(el('span',stagedSet.items.length+' reviewed drafts ready to apply together. Tests and acceptance remain on the plan.'),b);}
  }
  async function refreshSetStatus(){if(!root)return;try{pendingSet=await request('set_status');paintSet();}catch(e){report('editor',e);}}
  async function updateSetFiles(result){for(const row of result.files){const f=files.get(row.path);if(!f)continue;if(row.content===null&&f.pendingDeletion){files.delete(f.path);if(file===f){file=null;editor.show(editor.state('',''));}}else{f.original=row.content;f.changed=false;f.pendingDeletion=false;}}paintFiles();await list(folder);}
  async function applyStagedSet(){
    if(busy||!stagedSet||pendingSet)return;
    const set=stagedSet;busy=true;editor.readonly(true);sync();paintSet();
    try{
      for(const item of set.items){const f=files.get(item.path);if(!f||f.original!==item.original||f.draft!==(item.content===null?item.reference.draft:item.content)||!!f.pendingDeletion!==(item.content===null))throw Error('A staged draft changed. Review and stage the complete set again.');}
      for(const item of set.items)await verifyPlan(item.reference,item.content);
      const result=await request('apply_set',{files:set.items.map(({path,original,content})=>({path,original,content}))});
      stagedSet=null;await updateSetFiles(result);report('editor','All reviewed files applied. Return to the plan for checks and acceptance.');
    }catch(e){report('editor',e);}finally{busy=false;editor.readonly(!file||!!file.pendingDeletion);sync();await refreshSetStatus();paintSet();}
  }
  function confirmSetRecovery(restore){
    if(document.querySelector('#editor-set-confirmation'))return Promise.resolve(false);
    return new Promise(resolve=>{const dialog=el('dialog',undefined,'recovery-dialog');dialog.id='editor-set-confirmation';let accepted=false;
      dialog.append(el('h2',restore?'Restore original files?':'Finish applying these files?'),el('p',pendingSet.paths.join(', ')),el('p','Unrelated disk edits block this operation. Open Editor drafts will be preserved.'));
      dialog.append(button(restore?'Restore originals':'Finish applying','editor-set-confirm',()=>{accepted=true;dialog.close();}),button('Cancel','editor-set-cancel',()=>dialog.close()));
      dialog.addEventListener('close',()=>{dialog.remove();resolve(accepted);});document.body.append(dialog);dialog.showModal();
    });
  }
  async function recoverSet(restore){
    if(busy||!pendingSet)return;
    if(!await confirmSetRecovery(restore))return;
    busy=true;editor.readonly(true);sync();paintSet();
    try{const result=await request('recover_set',{restore});stagedSet=null;await updateSetFiles(result);report('editor',restore?'Original files restored. Open Editor drafts are preserved.':'File set applied. Open Editor drafts are preserved; review checks and acceptance on the plan.');}
    catch(e){report('editor',e);}finally{busy=false;editor.readonly(!file||!!file.pendingDeletion);sync();await refreshSetStatus();paintSet();}
  }
  const taskBar=el('div',undefined,'workbench-recovery');taskBar.id='editor-task-context';taskBar.hidden=true;const notices=el('div',undefined,'workbench-notices');notices.append(taskBar,recoveryBars.editor,setBar);pages.editor.querySelector('.workbench-toolbar').after(notices);
  function selectedTask(){if(!activeTask)return null;const task=heldProjection(current)?.development_tasks?.[activeTask.id];if(!task||runtimeWorld(current)!==activeTask.world||task.revision!==activeTask.revision||['cancelled','completed'].includes(task.status))throw Error('The development plan changed or is unavailable. Reopen it and prepare a fresh file request.');return task;}
  document.addEventListener('prepare-task-file',e=>{const task=heldProjection(current)?.development_tasks?.[e.detail.id];if(busy||!task||['cancelled','completed'].includes(task.status)||task.revision!==e.detail.revision||runtimeWorld(current)!==e.detail.world){e.preventDefault();return;}activeTask={...e.detail};taskBar.replaceChildren(el('span',`Plan: ${task.title}. Open the intended repository and file, then choose Discuss with bot. The app checks the repository against this plan before sharing and staging.`),button('Clear plan','editor-clear-task',()=>{activeTask=null;taskBar.hidden=true;publishEditor();}));const back=button('Return to plan','editor-return-task',()=>{});back.dataset.developmentTask=task.id;taskBar.append(back);taskBar.hidden=false;publishEditor();navigate('editor',true);report('editor','Choose the file to share with this plan’s assigned bot.');});
  const review=initChangeReview({el,button,body:bodies.editor,tree,editorHost,toolbar:pages.editor.querySelector('.workbench-toolbar'),request,report,openFile,onState:sync,discussPatch});
  const terminalHost=el('div',undefined,'terminal-host');terminalHost.id='terminal-output';bodies.terminal.append(terminalHost);
  const workerPicker=el('select');workerPicker.id='terminal-worker';workerPicker.setAttribute('aria-label','Runtime worker terminal');workerPicker.append(el('option','No runtime terminals'));
  pages.terminal.querySelector('.workbench-toolbar').append(workerPicker,button('Watch','terminal-watch',()=>watchWorker()));
  const url=el('input');url.id='browser-url';url.value='http://localhost:3000';url.setAttribute('aria-label','Local app address');
  const addressbar=pages.browser.querySelector('.workbench-toolbar');addressbar.replaceChildren(url,button('Go','browser-go',openBrowser),button('Reload','browser-reload',()=>browserAction('open',browser)),addressbar.querySelector('.surface-bot'),addressbar.lastElementChild);
  url.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();openBrowser();}};
  const viewport=bodies.browser;viewport.id='browser-viewport';viewport.append(el('p','Start your app in a terminal, then enter its local address.','workbench-empty'));
  function editorContext(){return {task:activeTask,root,session:surfaceSession,generation,busy:busy||review.open,files:[...files.values()].map(f=>({path:f.path,unsaved:f.draft!==f.original,selected:f===file}))};}
  function publishEditor(){publishTaskEditor(editorContext());}
  document.addEventListener('open-task-editor-file',e=>{const p=heldProjection(current),task=p?.development_tasks?.[e.detail.task?.id];if(!canOpenTaskEditor(p,task,runtimeWorld(current),editorContext(),e.detail)){e.preventDefault();return;}selectFile(files.get(e.detail.path));navigate('editor',true);});
  function sync(){for(const b of document.querySelectorAll("#editor-change-set button"))b.disabled=busy;publishEditor();for(const label of document.querySelectorAll('.workbench-root'))label.textContent=root??'No repository selected';for(const b of choosers)b.disabled=busy||[...shells.values()].some(s=>s.running);document.getElementById('editor-save').disabled=!file||file.pendingDeletion||file.draft===file.original||busy||review.open;document.getElementById('editor-reload').disabled=!file||busy||review.open;document.getElementById('editor-discuss').disabled=!file||review.open;document.getElementById('editor-share-files').disabled=!files.size||busy||review.open;document.getElementById('editor-changes').disabled=!root||busy;}
  function tab(bar,title,selected,select,close){const wrap=el('div',undefined,'workbench-tab'+(selected?' selected':''));const b=button(title,'',select);b.setAttribute('role','tab');b.setAttribute('aria-selected',String(selected));wrap.append(b);const x=button('×','',close);x.setAttribute('aria-label','Close '+title);wrap.append(x);bar.append(wrap);}
  function paintFiles(){bars.editor.replaceChildren();for(const f of files.values())tab(bars.editor,(f.pendingDeletion?'DELETE · ':f.draft!==f.original?'● ':'')+f.path.split('/').pop(),file===f,()=>selectFile(f),()=>{if(busy)return;if(f.draft!==f.original&&!confirm('Discard unsaved changes in '+f.path+'?'))return;files.delete(f.path);if(file===f){file=null;const next=files.values().next().value;if(next)selectFile(next);else{editor.show(editor.state('',''));editor.readonly(true);}}paintFiles();});if(!files.size)bars.editor.append(el('span','Editor','workbench-tab-label'));scheduleRecovery();report('editor',file?file.path+(file.pendingDeletion?' · Deletion staged':file.draft!==file.original?' · Unsaved':' · Saved')+(file.changed?' · Disk changed since recovery; saving checks for conflicts':''):'Open a repository and choose a file.');sync();}
  function selectFile(f){if(busy)return;review.hide();if(file)file.state=editor.current();file=f;editor.show(f.state);editor.readonly(!!f.pendingDeletion);paintFiles();}
  function addFile(path,content){if(files.has(path)){selectFile(files.get(path));return;}if(files.size>=16)throw new Error('Close a file tab before opening another.');const f={path,original:content,draft:content??'',state:editor.state(path,content??'')};files.set(path,f);selectFile(f);}
  async function openFile(path){if(busy)return;if(files.has(path))return selectFile(files.get(path));busy=true;try{const data=await request('read',{path});busy=false;addFile(data.path,data.content);}catch(e){report('editor',e);}finally{busy=false;sync();}}
  async function reloadFile(){if(!file||busy||(file.draft!==file.original&&!confirm('Discard your draft and reload '+file.path+'?')))return;const f=file;busy=true;try{const data=await request('read',{path:f.path});f.changed=false;f.original=f.draft=data.content;f.state=editor.state(f.path,f.draft);editor.show(f.state);paintFiles();}catch(e){report('editor',e);}finally{busy=false;sync();}}
  async function saveFile(){if(file?.pendingDeletion){report('editor','Use Apply staged change set to apply the reviewed deletion.');return;}if(review.open||!file||busy||file.draft===file.original)return;const f=file;busy=true;editor.readonly(true);sync();try{const data=await request('save',{path:f.path,original:f.original,content:f.draft});f.changed=false;f.original=data.content;paintFiles();await list(folder);}catch(e){report('editor',e);}finally{busy=false;editor.readonly(false);sync();}}
  async function list(path){if(!root)return;try{const data=await request('list',{path});folder=data.path;entries.replaceChildren(el('div',folder||'/','development-folder'));for(const entry of data.entries){const path=[folder,entry.name].filter(Boolean).join('/');const b=button((entry.directory?'▸ ':'')+entry.name,'',()=>entry.directory?list(path):openFile(path));b.dataset.filePath=path;b.dataset.directory=String(entry.directory);b.title=path;entries.append(b);}if(data.truncated)entries.append(el('p','First 1,000 entries'));}catch(e){report('editor',e);}}
  async function choose(){if(busy)return;persistRecovery();if([...files.values()].some(f=>f.draft!==f.original)&&!confirm('Switch repository and close these drafts? The latest successful recovery copy will remain on this device.'))return;busy=true;sync();try{const s=await invoke('choose_workbench');if(s.cancelled)return;projectReady=false;root=s.root;generation=s.generation;stagedSet=null;pendingSet=null;paintSet();review.reset();files.clear();file=null;editor.show(editor.state('',''));editor.readonly(true);for(const t of shells.values()){t.term.dispose();t.host.remove();}shells.clear();shell=null;await list('');await restoreProject();paintFiles();paintShells();}catch(e){report(active in pages?active:'editor',e);}finally{busy=false;sync();}}
  function paintShells(){const signature=JSON.stringify([root,[...shells.values()].map(s=>[s.id,s.running]),shell?.id,worker?.id]);if(signature===shellSignature)return;shellSignature=signature;scheduleRecovery();bars.terminal.replaceChildren();for(const s of shells.values())tab(bars.terminal,'Shell '+s.id+(s.running?'':' · exited'),shell===s&&!worker,()=>selectShell(s),async()=>{if(!confirm('Close shell '+s.id+' and stop its foreground command?'))return;try{await request('close_shell',{id:s.id});shellReady=true;s.closed=true;s.term.dispose();s.host.remove();shells.delete(s.id);if(shell===s)shell=null;paintShells();const next=shells.values().next().value;if(next&&!worker)selectShell(next);}catch(e){report('terminal',e);}});if(worker)tab(bars.terminal,'Worker '+worker.id,true,()=>{},()=>{worker=null;invoke('terminal_surface',{open:false}).catch(e=>report('terminal',e));paintShells();if(shell)selectShell(shell);});const add=button('+','terminal-new',newShell);add.setAttribute('aria-label','New shell');add.disabled=!root||shells.size>=8;bars.terminal.append(add);sync();}
  function registerShell(data){if(shells.has(data.id)){shells.get(data.id).running=data.running;return;}const host=el('div',undefined,'shell-terminal');host.hidden=true;terminalHost.append(host);const term=new window.Terminal({cursorBlink:true,fontSize:13,fontFamily:'ui-monospace, monospace',scrollback:3000,theme:{background:'#0d1420',foreground:'#dbe7f6',cursor:'#9ac5ff'}});term.open(host);const s={id:data.id,term,host,offset:0,running:data.running??true,reading:false,closed:false,input:Promise.resolve(),queued:0};shells.set(s.id,s);term.onData(data=>{if(s.closed||!s.running)return;if(s.queued+data.length>65536){report('terminal','Paste is too large. Wait for the current input to finish.');return;}s.queued+=data.length;s.input=s.input.then(async()=>{for(let at=0;at<data.length;){let end=Math.min(at+512,data.length);if(end<data.length&&/[\uD800-\uDBFF]/.test(data[end-1]))end--;const chunk=data.slice(at,end);if(s.closed)return;await request('shell_input',{id:s.id,data:chunk});at=end;}}).catch(e=>report('terminal',e)).finally(()=>s.queued-=data.length);});}
  async function newShell(){if(!root||busy)return;shellReady=true;busy=true;try{const data=await request('open_shell');registerShell(data);selectShell(shells.get(data.id));}catch(e){report('terminal',e);}finally{busy=false;sync();}}
  function selectShell(s){worker=null;invoke('browser_surface',{action:'worker_hide'}).catch(()=>{});shell=s;for(const t of shells.values())t.host.hidden=t!==s;paintShells();requestAnimationFrame(()=>{fit();s.term.focus();readShell(s);});report('terminal','Interactive shell '+s.id+' · '+root);}
  function fit(){if(active!=='terminal'||worker||!shell)return;const t=shell.term,cell=t._core?._renderService?.dimensions?.css?.cell;if(!cell?.width||!cell.height)return;const cols=Math.max(2,Math.min(400,Math.floor((terminalHost.clientWidth-16)/cell.width))),rows=Math.max(2,Math.min(160,Math.floor((terminalHost.clientHeight-12)/cell.height)));if(cols!==t.cols||rows!==t.rows){t.resize(cols,rows);request('shell_resize',{id:shell.id,cols,rows}).catch(e=>report('terminal',e));}}
  async function readShell(s){if(s.reading||s.closed)return;s.reading=true;try{const data=await request('shell_output',{id:s.id,after:s.offset});if(s.closed)return;if(data.omitted)s.term.writeln('\r\n[Older terminal output omitted]\r\n');await new Promise(resolve=>s.term.write(new Uint8Array(data.data),resolve));s.offset=data.next;s.running=data.running;}catch(e){report('terminal',e);}finally{s.reading=false;}}
  function paintWorkers(){const p=heldProjection(current),selected=workerPicker.value;const list=Object.values(p?.workers??{}).filter(w=>w.status==='open'&&w.terminal==='PRESENT');const signature=JSON.stringify([!!p,list,p?.bots,p?.lanes,workerWorld]);if(signature===workerSignature)return;workerSignature=signature;workerPicker.replaceChildren();const placeholder=el('option',p?'Runtime terminals ('+list.length+')':'Runtime unavailable');placeholder.value='';workerPicker.append(placeholder);for(const w of list){const lane=p.lanes?.[w.locus_ref],bot=Object.values(p.bots??{}).find(b=>b.actor===lane?.actor);const o=el('option',(bot?.name||w.purpose||'Worker')+' · '+w.id);o.value=w.id;workerPicker.append(o);}workerPicker.value=list.some(w=>w.id===selected)?selected:'';if(worker&&(!list.some(w=>w.id===worker.id&&w.generation===worker.generation)||workerWorld!==runtimeWorld(current))){worker=null;invoke('terminal_surface',{open:false}).catch(()=>{});report('terminal','The watched worker is no longer available.');paintShells();}}
  async function watchWorker(id=workerPicker.value){const w=heldProjection(current)?.workers?.[id];if(!w||w.status!=='open'||w.terminal!=='PRESENT')return;worker=w;workerWorld=runtimeWorld(current);for(const s of shells.values())s.host.hidden=true;try{if(!await apply('terminal_bind',{worker_ref:w.id,expected_worker_generation:w.generation??1}))throw new Error('Worker terminal binding was refused. Check Activity.');paintShells();layout();report('terminal','Worker '+w.id+' · Live observation · Read only');}catch(e){worker=null;invoke('terminal_surface',{open:false}).catch(()=>{});report('terminal',e);}}
  function paintBrowsers(){const signature=JSON.stringify([browser?.id,[...browsers.values()].map(b=>[b.id,b.url])]);if(signature===browserSignature)return;browserSignature=signature;scheduleRecovery();bars.browser.replaceChildren();for(const b of browsers.values())tab(bars.browser,b.url?new URL(b.url).host:'New tab',browser===b,()=>{browser=b;url.value=b.url||'http://localhost:3000';paintBrowsers();if(b.restored){b.restored=false;browserAction('open',b);}else layout();},async()=>{await browserAction('close',b);browserReady=true;browsers.delete(b.id);if(browser===b)browser=browsers.values().next().value??null;paintBrowsers();if(browser){url.value=browser.url;layout();}});const add=button('+','browser-new',()=>{if(browsers.size>=8)return;browserReady=true;const id=Array.from({length:8},(_,i)=>i).find(i=>!browsers.has(i));browser={id,url:'',token:crypto.randomUUID()};browsers.set(id,browser);url.value='http://localhost:3000';paintBrowsers();browserAction('hide_all');url.focus();});add.setAttribute('aria-label','New browser tab');bars.browser.append(add);}
  function rect(id){const r=bodies[id].getBoundingClientRect();return{x:Math.max(4,r.x),y:r.y,width:Math.max(0,Math.min(r.right,innerWidth-6)-Math.max(4,r.x)),height:Math.max(0,Math.min(r.bottom,innerHeight-6)-r.y)};}
  function browserAction(action,b=browser){const address=b?.url;surfaceTail=surfaceTail.catch(()=>{}).then(async()=>{const visible=active==='browser'&&!document.querySelector('dialog[open],.desktop-menu:not([hidden])');if(['open','layout'].includes(action)&&(!visible||browser!==b||!b?.url))return;return invoke('browser_surface',{action,tab:b?.id??0,url:action==='open'?address:null,rect:['open','layout','worker_layout'].includes(action)?rect(action==='worker_layout'?'terminal':'browser'):null});}).catch(e=>report(active==='terminal'?'terminal':'browser',e));return surfaceTail;}
  function openBrowser(){browserReady=true;try{const parsed=new URL(url.value);if(!['http:','https:'].includes(parsed.protocol)||!['localhost','127.0.0.1','[::1]'].includes(parsed.hostname)||parsed.username||parsed.password)throw new Error('Enter a local HTTP or HTTPS address.');if(!browser){document.getElementById('browser-new').click();}browser.url=parsed.href;url.value=browser.url;paintBrowsers();browserAction('open',browser);report('browser',browser.url);}catch(e){report('browser',e);}}
  function layout(){cancelAnimationFrame(layoutFrame);layoutFrame=requestAnimationFrame(()=>{const covered=document.querySelector('dialog[open],.desktop-menu:not([hidden])');const signature=JSON.stringify([active,!!covered,browser?.id,browser?.url,worker?.id,active in bodies?rect(active):null]);if(signature===lastSurface)return;lastSurface=signature;if(active==='browser'&&!covered&&browser?.url){if(browser.restored){browser.restored=false;browserAction('open');}else browserAction('layout');}else browserAction('hide_all');if(active==='terminal'&&worker&&!covered)browserAction('worker_layout');else browserAction('worker_hide');fit();});}
  for(const id of ['terminal','browser']){const toolbar=pages[id].querySelector('.workbench-toolbar');toolbar.append(button('Link to bot',id+'-link-bot',async()=>{const botId=toolbar.querySelector('.surface-bot').value;try{if(id==='terminal'&&(!shell||worker))throw Error('Choose a local shell tab. Runtime worker ownership is shown under Assigned work.');if(id==='browser'&&!browser?.url)throw Error('Open a browser tab first.');await surfaceTail;await links.link({kind:id,id:id==='terminal'?shell.id:browser.id,generation},botId);report(id,'Linked to '+(createBotRoster(localStorage).get(botId)?.name||botId)+' · Open its Work tab to return here.');}catch(e){report(id,e);}}));}
  document.addEventListener('open-linked-session',async e=>{try{const row=await links.resolve(e.detail.id,e.detail.botId);if(row.kind==='terminal'){const state=await request('status');if(state.generation!==row.generation)throw Error('This session belongs to a different repository.');for(const s of state.shells??[])registerShell(s);const target=shells.get(row.id);if(!target)throw Error('The shell has closed.');navigate('terminal');selectShell(target);}else{const state=await invoke('browser_surface',{action:'status'}),target=state.tabs.find(b=>b.id===row.id);if(!target)throw Error('The browser tab has closed.');if(!browsers.has(target.id))browsers.set(target.id,{...target,token:crypto.randomUUID()});browser=browsers.get(target.id);browser.url=target.url;url.value=target.url;navigate('browser');paintBrowsers();layout();}}catch(error){alert(String(error));}});
  async function verifyPlan(reference,proposed){
    if(!reference.task)return;
    const match=await request('match_plan',{generation:reference.generation,task_ref:reference.task.id,revision:reference.task.revision,world:JSON.parse(reference.task.world)});
    if(!match.matched||match.task_ref!==reference.task.id||match.revision!==reference.task.revision||JSON.stringify(match.world)!==reference.task.world)throw Error('The repository match is no longer current. Reopen the plan and file.');
    if(reference.source){
      const basis=await request(proposed===null?'delete_basis':'file_basis',{generation:reference.generation,path:reference.key,original:reference.original,draft:reference.draft,...(proposed===null?{}:{proposed:proposed??null})});
      if(basis.basis_id!==reference.source.basis_id)throw Error('The source commit or file changed. Share a fresh snapshot before using this proposal.');
      return {...basis,task_ref:match.task_ref,task_revision:match.revision,repository_ref:match.repository_ref,world:match.world};
    }
    return match;
  }
  function shareRelatedFiles(botId){
    if(busy||review.open||document.querySelector('#related-files-dialog'))return;
    const dialog=el('dialog',undefined,'file-proposal-review');dialog.id='related-files-dialog';
    dialog.append(el('h2','Share related files'),el('p','Choose up to four open files. Complete current drafts will be attached to the bot; nothing is sent until you press Send. Edits returned together can be reviewed and staged together. Use Apply staged change set after reviewing a combined proposal.','directory-note'));
    const form=el('form'),choices=el('div'),notice=el('p','','availability-note');notice.setAttribute('role','status');
    for(const f of files.values()){const label=el('label',undefined,'connection-row'),input=el('input');input.type='checkbox';input.value=f.path;input.checked=f===file;input.dataset.relatedFile=f.path;label.append(input,el('span',f.path+' · '+new TextEncoder().encode(f.draft).length+' bytes'+(f.draft!==f.original?' · Unsaved draft':'')));choices.append(label);}
    const submit=el('button','Attach selected files','primary');submit.type='submit';submit.id='related-files-attach';const cancel=button('Cancel','related-files-cancel',()=>dialog.close());form.append(choices,notice,submit,cancel);dialog.append(form);document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();
    form.onsubmit=async event=>{
      event.preventDefault();if(busy)return;let task,capturedTask=activeTask,capturedGeneration=generation,selection;
      try{
        selection=relatedFileSelection([...choices.querySelectorAll('input:checked')].map(input=>files.get(input.value)));
        task=selectedTask();if(task){const b=heldProjection(current)?.bots?.[task.bot_ref];if(!b)throw Error('The assigned bot is unavailable.');botId=b.client_ref;}
        busy=true;submit.disabled=true;cancel.disabled=true;for(const input of choices.querySelectorAll('input'))input.disabled=true;sync();notice.textContent='Checking the selected files…';
        const items=[];
        for(const selected of selection){
          const ref={kind:'editor',key:selected.path,generation:capturedGeneration,title:selected.path,original:selected.original,draft:selected.draft,session:surfaceSession};let content=selected.path+'\n\n'+selected.draft;
          if(task){ref.task={id:task.id,revision:task.revision,world:capturedTask.world};const match=await verifyPlan(ref);ref.source=await request('file_basis',{generation:capturedGeneration,path:ref.key,original:ref.original,draft:ref.draft,proposed:null});content=taskFileAttachment(task,ref.key,ref.draft,match,ref.source);}
          items.push({reference:ref,attachment:{name:ref.title.slice(0,120),content}});
        }
        if(!dialog.open)throw Error('File selection was closed. No files were attached.');
        if(generation!==capturedGeneration||activeTask!==capturedTask||selection.some(s=>files.get(s.path)!==s.file||s.file.draft!==s.draft||s.file.original!==s.original)||task&&selectedTask()?.revision!==task.revision)throw Error('A selected file or plan changed while checking. Select the files again.');
        navigate('bot:'+botId);const attach=new CustomEvent('bot-surface-context',{cancelable:true,detail:{botId,items}});if(!document.dispatchEvent(attach))throw Error(attach.detail.error||'Could not attach the selection. Finish the current bot operation or remove an attachment first.');dialog.close();
      }catch(error){notice.textContent=String(error.message||error);}finally{busy=false;if(dialog.open){submit.disabled=false;cancel.disabled=false;for(const input of choices.querySelectorAll('input'))input.disabled=false;}sync();}
    };
  }
  async function discuss(id,botId){let task;try{task=id==='editor'?selectedTask():null;if(task){const b=heldProjection(current)?.bots?.[task.bot_ref];if(!b)throw Error('The assigned bot is unavailable.');botId=b.client_ref;}}catch(e){return report(id,e.message||e);}let ref,content;if(id==='editor'&&file){ref={kind:id,key:file.path,generation,title:file.path,original:file.original,...(new TextEncoder().encode(file.draft).length<=24000?{draft:file.draft}:{})};content=file.path+'\n\n'+new TextDecoder().decode(new TextEncoder().encode(file.draft).slice(0,24000));}else if(id==='terminal'&&(worker||shell)){ref={kind:id,key:worker?'worker:'+worker.id:shell.id,generation,world:workerWorld,title:worker?'Worker '+worker.id:'Shell '+shell.id};const buffer=shell&&!worker?shell.term.buffer.active:null;const lines=[];if(buffer)for(let i=Math.max(0,buffer.length-200);i<buffer.length;i++)lines.push(buffer.getLine(i)?.translateToString(true)??'');content=ref.title+'\nRepository: '+root+'\n'+new TextDecoder().decode(new TextEncoder().encode(lines.join('\n')).slice(-16000));}else if(id==='browser'&&browser?.url){ref={kind:id,key:browser.id,token:browser.token,title:browser.url};content='Browser tab: '+browser.url;}else{return report(id,'Open a '+id+' tab first.');}if(task){if(typeof ref.draft!=='string')return report(id,'This file is too large for a complete plan-linked proposal. Choose a smaller file.');ref.task={id:task.id,revision:task.revision,world:activeTask.world};try{const capturedFile=file,capturedTask=activeTask;const match=await verifyPlan(ref);ref.source=await request('file_basis',{generation:ref.generation,path:ref.key,original:ref.original,draft:ref.draft,proposed:null});if(file!==capturedFile||file.draft!==ref.draft||file.original!==ref.original||generation!==ref.generation||activeTask!==capturedTask||selectedTask()?.revision!==task.revision)throw Error('The plan or file changed while checking its repository. Share it again.');content=taskFileAttachment(task,file.path,ref.draft,match,ref.source);}catch(e){return report(id,e.message||e);}}ref.session=surfaceSession;navigate('bot:'+botId);const event=new CustomEvent('bot-surface-context',{cancelable:true,detail:{botId,reference:ref,attachment:{name:ref.title.slice(0,120),content}}});if(!document.dispatchEvent(event))report(id,'Could not attach this context. Finish the current bot operation first.');}
  document.addEventListener('review-file-proposal-set',e=>{try{
    if(busy)throw Error('Finish the current file operation first.');
    const items=e.detail.items;
    const state=r=>({session:surfaceSession,generation,file:files.get(r.key),task:heldProjection(current)?.development_tasks?.[r.task?.id],world:runtimeWorld(current)});
    reviewProposalSet({items,current:state,record:recordSet?async material=>{
      checkProposalSet(items,state);
      const ref=items[0].reference,origin=runtimeWorld(current);
      const client_ref=items.reviewRequest??=crypto.randomUUID();
      if(!await recordSet({client_ref,task_ref:ref.task.id,task_revision:ref.task.revision,material}))throw Error('The runtime did not confirm the combined review. Check Activity; retrying keeps the same request identity.');
      let saved;await waitForBot(current,origin,p=>{saved=Object.values(p.development_attempts??{}).find(a=>a.client_ref===client_ref);return !!saved;});
      return saved.id;
    }:null,verify:(r,text)=>verifyPlan(r,text),stage:drafts=>{
      if(busy)throw Error('The editor is busy. Try again.');
      checkProposalSet(items,state);
      // Allocate every Editor state before changing any open file.
      const prepared=drafts.map(d=>{const target=files.get(d.path),draft=d.text===null?target.draft:d.text;return {target,draft,deletion:d.text===null,state:editor.state(d.path,draft)};});
      review.hide();
      for(const p of prepared){p.target.draft=p.draft;p.target.state=p.state;p.target.pendingDeletion=p.deletion;}
      stagedSet={items:prepared.map((p,i)=>({path:p.target.path,original:p.target.original,content:p.deletion?null:p.draft,reference:items[i].reference}))};
      file=prepared[0].target;editor.show(file.state);editor.readonly(!!file.pendingDeletion);paintFiles();paintSet();
      report('editor',prepared.length+' bot drafts staged together · Use Apply staged change set to save the complete set');
    },navigate,el,button});
  }catch(error){e.detail.error=String(error.message||error);e.preventDefault();}});
  document.addEventListener('review-file-proposal',e=>{try{if(busy)throw Error('Finish the current file operation first.');const reference=e.detail.reference;const target=files.get(reference?.key);reviewFileProposal({reference,proposal:e.detail.proposal,verify:()=>verifyPlan(reference,e.detail.proposal.content),onIdentity:e.detail.onIdentity,recordAttempt:reference?.task&&recordAttempt?async source=>{
      const origin=runtimeWorld(current);
      if(origin!==reference.task.world)throw Error('The runtime changed. Reopen the review.');
      reference.attemptRequests??={};
      const client_ref=reference.attemptRequests[source.result_sha256]??=crypto.randomUUID();
      const args={client_ref,task_ref:reference.task.id,task_revision:reference.task.revision,source,shared_draft:reference.draft,proposed_text:e.detail.proposal.content};
      if(!await recordAttempt(args))throw Error('The runtime did not confirm the review record. Check Activity; retrying keeps the same request identity.');
      let saved;await waitForBot(current,origin,p=>{saved=Object.values(p.development_attempts??{}).find(a=>a.client_ref===client_ref);return !!saved;});
      return saved.id;
    }:null,current:()=>({session:surfaceSession,generation,file:files.get(reference?.key),task:heldProjection(current)?.development_tasks?.[reference?.task?.id],world:runtimeWorld(current)}),stage:text=>{if(busy)throw Error('The editor is busy. Try again.');review.hide();selectFile(target);editor.replace(text);report('editor',target.path+' · Bot proposal staged as unsaved draft · Review, then Save');},navigate,el,button});}catch(error){e.detail.error=String(error);e.preventDefault();}});
  document.addEventListener('watch-runtime-worker',e=>{const r=e.detail,w=heldProjection(current)?.workers?.[r.id];if(r.world!==runtimeWorld(current)||!w||(w.generation??1)!==r.generation||w.status!=='open'||w.terminal!=='PRESENT')return;navigate('terminal');workerPicker.value=w.id;watchWorker(w.id);});
  document.addEventListener('open-development-surface',e=>{const r=e.detail;const ok=r.session===surfaceSession&&(r.kind==='browser'?browsers.get(r.key)?.token===r.token:r.generation===generation);if(!ok){alert('This surface has closed or its repository changed.');return;}if(r.kind==='changes'){navigate('editor');review.showPath(r.key);return;}if(r.kind==='editor'){const f=files.get(r.key);if(!f){alert('That file tab is closed.');return;}navigate('editor');selectFile(f);}else if(r.kind==='terminal'){if(typeof r.key==='string'){if(!worker||r.world!==workerWorld||r.key!=='worker:'+worker.id){alert('That worker is no longer being watched.');return;}navigate('terminal');layout();}else{const s=shells.get(r.key);if(!s){alert('That shell is closed.');return;}navigate('terminal');selectShell(s);}}else{browser=browsers.get(r.key);url.value=browser.url;navigate('browser');paintBrowsers();layout();}});
  async function poll(){if(polling||busy)return;polling=true;try{if(active==='terminal'&&shell&&!worker)await readShell(shell);const now=performance.now();if(now-lastInventoryPoll<2000)return;lastInventoryPoll=now;const s=await request('status');if(s.root&&!root){root=s.root;generation=s.generation;busy=true;try{await list('');await restoreProject();}finally{busy=false;}}if(s.shells?.length)shellReady=true;for(const data of s.shells??[])registerShell(data);paintShells();paintWorkers();if(active==='browser'&&now-lastBrowserPoll>=2000){lastBrowserPoll=now;const state=await invoke('browser_surface',{action:'status'});for(const b of state.tabs??[]){if(b.url){browserReady=true;if(!browsers.has(b.id)){browsers.set(b.id,{...b,token:crypto.randomUUID()});paintBrowsers();}else{browsers.get(b.id).url=b.url;browsers.get(b.id).restored=false;}}}paintBrowsers();if(browser&&document.activeElement!==url&&url.value!==browser.url)url.value=browser.url;}sync();}catch(e){report('terminal',e);}finally{polling=false;}}
  document.addEventListener('page-selected',e=>{active=e.detail.id;document.body.classList.toggle('development-active',active in pages);for(const [id,p] of Object.entries(pages))p.hidden=id!==active;lastSurface='';lastInventoryPoll=-Infinity;if(active==='terminal'&&!shell&&shells.size)selectShell(shells.values().next().value);layout();});
  new ResizeObserver(layout).observe(canvas);new ResizeObserver(fit).observe(terminalHost);window.addEventListener('resize',layout);
  new MutationObserver(layout).observe(document.getElementById('desktop-chrome'),{subtree:true,attributes:true,attributeFilter:['hidden']});
  new MutationObserver(records=>{if(records.some(r=>r.target.matches?.('dialog,.desktop-menu')||[...r.addedNodes].some(n=>n.matches?.('dialog')||n.querySelector?.('dialog'))))layout();}).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['open','hidden']});
  document.addEventListener('click',e=>{if(e.target.closest('[data-window-action="close"]')&&[...files.values()].some(f=>f.draft!==f.original)&&!persistRecovery()&&!confirm('Recovery could not save. Close Super and discard unsaved file drafts?')){e.preventDefault();e.stopImmediatePropagation();}},true);
  window.addEventListener('beforeunload',persistRecovery);
  function scheduleRecovery(){if(recovering)return;clearTimeout(recoveryTimer);recoveryTimer=setTimeout(persistRecovery,500);}
  function persistRecovery(){clearTimeout(recoveryTimer);if(recovering)return false;try{if(projectReady&&root)recoveryStore.saveProject({root,selected:file?.path??null,files:[...files.values()].map(f=>f.draft!==f.original?{path:f.path,dirty:true,original:f.original,draft:f.draft}:{path:f.path,dirty:false})});if(browserReady||shellReady){const old=recoveryStore.snapshot();recoveryStore.saveSurfaces(browserReady?[...browsers.values()].filter(b=>b.url).map(b=>b.url):old.browsers,shellReady?shells.size:old.shells);}recoveryProblem=recoveryStore.error||'';paintRecovery();return !recoveryProblem;}catch(e){recoveryProblem=String(e.message||e);paintRecovery();return false;}}
  function paintRecovery(){const messages=[];if(recoveryProblem)messages.push(recoveryProblem);else if(!root&&initialRecovery.projects.length)messages.push('Recovery available · Choose the same repository to reopen saved files and drafts.');else if(projectReady)messages.push('Recovery enabled for file tabs and drafts on this device.');if(!shellReady&&initialRecovery.shells)messages.push(initialRecovery.shells+' previous shell tab(s) ended. Commands have not been restarted.');const canRestore=!browserReady&&!browsers.size&&initialRecovery.browsers.length;const signature=JSON.stringify([messages,canRestore]);for(const bar of Object.values(recoveryBars)){if(bar.dataset.signature===signature)continue;bar.dataset.signature=signature;bar.replaceChildren(el('span',messages.join(' ')));bar.hidden=!messages.length&&!canRestore;if(canRestore)bar.append(button('Restore browser tabs','',restoreBrowsers));}}
  async function restoreProject(){recovering=true;const saved=recoveryStore.get(root);const notes=[];try{if(saved){for(const record of saved.files){let disk=null;try{disk=(await request('read',{path:record.path})).content;}catch(e){if(!record.dirty){notes.push(record.path+': '+e);continue;}}const data=recoveryFile(record,disk);const restored={...data,state:editor.state(data.path,data.draft)};files.set(restored.path,restored);if(data.changed)notes.push(record.path+': disk differs from the recovered draft’s original. Save will check for conflicts.');}file=files.get(saved.selected)??files.values().next().value??null;if(file)editor.show(file.state);}projectReady=true;}finally{recovering=false;}paintFiles();if(notes.length)report('editor',notes.join(' · '));paintRecovery();await refreshSetStatus();}
  async function restoreBrowsers(){if(browserReady||browsers.size)return;try{const existing=await invoke('browser_surface',{action:'status'});const tabs=(existing.tabs??[]).filter(b=>b.url);if(tabs.length){for(const b of tabs)browsers.set(b.id,{...b,token:crypto.randomUUID()});}else{initialRecovery.browsers.forEach((url,id)=>browsers.set(id,{id,url,restored:true,token:crypto.randomUUID()}));}browser=browsers.values().next().value??null;browserReady=true;if(browser)url.value=browser.url;paintBrowsers();persistRecovery();layout();}catch(e){recoveryProblem=String(e);paintRecovery();}}
  function manageRecovery(){const dialog=el('dialog',undefined,'recovery-dialog');dialog.append(el('h2','Workbench recovery'),el('p','Saved on this device. Restore files by choosing their repository. Shell commands are never restarted automatically.'));for(const p of recoveryStore.snapshot().projects){const row=el('div',undefined,'recovery-project');row.append(el('span',p.root+' · '+p.files.filter(f=>f.dirty).length+' unsaved draft(s)'),button('Forget copy','',()=>{if(!confirm('Delete this repository’s recovery copy? Saved files on disk and currently open drafts remain.'))return;try{recoveryStore.forget(p.root);row.remove();}catch(e){recoveryProblem=String(e);paintRecovery();}}));dialog.append(row);}dialog.append(button('Clear recovery data','',()=>{if(!confirm('Delete all saved recovery copies? This cannot be undone. Open drafts and files on disk remain.'))return;try{recoveryStore.clear();initialRecovery.projects=[];initialRecovery.browsers=[];initialRecovery.shells=0;recoveryProblem='';paintRecovery();dialog.close();}catch(e){recoveryProblem=String(e);paintRecovery();}}),button('Close','',()=>dialog.close()));dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal();}
  pages.editor.querySelector('.workbench-toolbar').append(button('Recovery','workbench-recovery-manage',manageRecovery));
  function discussPatch(diff){const botId=pages.editor.querySelector('.surface-bot').value;const reference={kind:'changes',key:diff.path,generation,session:surfaceSession,title:'Changes: '+diff.path};navigate('bot:'+botId);const event=new CustomEvent('bot-surface-context',{cancelable:true,detail:{botId,reference,attachment:{name:('Changes: '+diff.path).slice(0,120),content:patchAttachment(diff)}}});if(!document.dispatchEvent(event))report('editor','Could not attach this patch. Finish the current bot operation first.');}
  paintRecovery();
  document.addEventListener('runtime-view-rendered',paintWorkers);document.addEventListener('runtime-view-rendered',publishEditor);
  new MutationObserver(paintWorkers).observe(document.getElementById('world'),{childList:true});
  paintFiles();paintShells();paintBrowsers();setInterval(poll,200);poll();
}
