import {node} from './app-shell.js';
import {reviewBasis,sameBasis,parseFindings,reviewPrompt,runIdentity} from './visual-review-model.js';

export function visualReview({task,request,invoke,current,getRecord,onSaved}) {
 const panel=node('section',undefined,'visual-review attempt-checks'),criteriaText=node('p',task.criteria||'No requirements recorded.');criteriaText.style.whiteSpace='pre-line';panel.append(node('h4','Check against requirements'),criteriaText);
 const cancel=node('button','Cancel review');cancel.type='button';cancel.hidden=true;
 const model=node('select'),effort=node('select');model.setAttribute('aria-label','Visual review model');effort.setAttribute('aria-label','Visual review effort');
 const evidenceSelect=node('select'),provider=node('select'),run=node('button','Review before and after'),status=node('p'),findings=node('div'),context=node('div');
 evidenceSelect.setAttribute('aria-label','Review evidence');provider.setAttribute('aria-label','Visual review provider');run.type='button';status.setAttribute('role','status');
 for(const [id,title] of [['claude','Claude connection'],['anthropic','Anthropic API'],['openai','OpenAI API'],['ollama','Local Ollama']]){const option=node('option',title);option.value=id;provider.append(option);}
 const assigned=current()?.frame?.projection?.bots?.[task.bot_ref],suffix=assigned?.client_ref&&assigned.client_ref!=='assistant'?':bot:'+assigned.client_ref:'';
 let preferences=[];try{preferences=JSON.parse(localStorage.getItem('super-provider-preferences'+suffix)||'[]');}catch{}
 const preferred=localStorage.getItem('super-last-provider'+suffix);if([...provider.options].some(o=>o.value===preferred))provider.value=preferred;
 panel.append(node('p','Choose a connected provider with image support. Review sends these two images, task requirements and selected evidence to that provider. It cannot accept the task.','directory-note'),provider,model,effort,evidenceSelect,context,run,cancel,status,findings);
 let visualPreferences={};try{visualPreferences=JSON.parse(localStorage.getItem('super-visual-review-preferences')||'{}');}catch{}
 let catalogGeneration=0;
 function selectedSettings(){return {...(preferences.find(([p])=>p===provider.value)?.[1]||{}),...(visualPreferences[provider.value]||{})};}
 function remember(){visualPreferences[provider.value]={model:model.value,effort:effort.value};localStorage.setItem('super-visual-review-preferences',JSON.stringify(visualPreferences));}
 async function models(){const generation=++catalogGeneration,p=provider.value,saved=selectedSettings();model.replaceChildren();effort.replaceChildren();for(const level of ['', 'low','medium','high','xhigh','max']){const o=node('option',level?'Effort: '+level:'Provider default effort');o.value=level;effort.append(o);}effort.value=saved.effort||saved.efforts?.[saved.model]||'';effort.hidden=p!=='claude';const seed=node('option',saved.model||'Current model');seed.value=saved.model||'';model.append(seed);try{const result=await invoke(p==='claude'?'bot_claude_connection':p==='ollama'?'bot_local_models':'bot_models',p==='claude'?{operation:'models'}:p==='ollama'?{endpoint:saved.endpoint||'http://127.0.0.1:11434'}:{provider:p});if(generation!==catalogGeneration)return;const rows=result.models||[];model.replaceChildren();for(const m of rows){const id=typeof m==='string'?m:m.id,o=node('option',typeof m==='string'?m:m.name||m.id);o.value=id;model.append(o);}if(saved.model){if(![...model.options].some(o=>o.value===saved.model)){const o=node('option',saved.model+' (saved choice)');o.value=saved.model;model.append(o);}model.value=saved.model;}}catch{if(generation===catalogGeneration&&!saved.model)status.textContent='Connect this provider in Bot settings before reviewing.';}}
 provider.onchange=()=>{models();draw();};model.onchange=remember;effort.onchange=remember;
 let choices=[null],busy=false,requestId=null;
 cancel.onclick=async()=>{cancel.disabled=true;try{await invoke('bot_claude_connection',{operation:'cancel_reply',requestId});status.textContent='Cancelling review…';}catch(e){status.textContent=String(e);cancel.disabled=false;}};
 function taskCurrent(){const c=current(),w=c?.frame?.world,t=c?.frame?.projection?.development_tasks?.[task.id];return panel.isConnected&&!c.withdrawn&&!c.unavailable&&!c.stalled&&JSON.stringify([w?.world_incarnation,w?.world_generation])===JSON.stringify(request.world)&&t?.revision===task.revision&&t.criteria===task.criteria;}
 function evidence(){return choices[Number(evidenceSelect.value)]||null;}
 function basis(){return reviewBasis(task,getRecord(),evidence());}
 function evidenceCurrent(){const e=evidence();if(!e)return true;const a=current()?.frame?.projection?.development_attempts?.[e.attempt];return a?.revision===e.attempt_revision&&runIdentity(a.test_runs)===e.test_runs_identity;}
 function valid(){if(!taskCurrent()||!evidenceCurrent())throw Error('The task or review evidence changed. Reopen the task.');}
 function draw(){
  const record=getRecord(),review=record.review;run.disabled=busy||!record.images?.before||!record.images?.after;provider.disabled=busy;evidenceSelect.disabled=busy;model.disabled=busy;effort.disabled=busy;cancel.hidden=!busy||provider.value!=='claude';
  context.replaceChildren(node('p',evidence()?`Linked to ${evidence().label}. Capture origin is unverified.`:'No tested result linked. This is an image-only review.','directory-note'));
  const linked=evidence();if(linked){const details=node('details');details.append(node('summary','Recorded checks and build identity'),node('p','Source snapshot: '+linked.snapshot,'directory-note'));if(linked.executable)details.append(node('p','Executable: '+linked.executable,'directory-note'));for(const check of linked.checks||[])details.append(node('p',`${check.profile||'Check'}: ${check.outcome||check.state}${check.snapshot!==linked.snapshot?' · different source snapshot':''}`,'directory-note'));if(task.required_checks?.profiles)details.append(node('p','Required profiles: '+task.required_checks.profiles.join(', '),'directory-note'));context.append(details);}
  findings.replaceChildren();if(!review)return;
  const stale=!sameBasis(review.basis,basis())||!evidenceCurrent();
  findings.append(node('h4',stale?'Previous review — evidence changed':review.inspected_at?'AI findings · inspected':'AI findings · needs your inspection'),node('p',`${review.provider} · ${review.model||'configured model'} · ${new Date(review.at).toLocaleString()}`,'directory-note'),node('p',review.findings.summary));
  for(const item of review.findings.requirements){const row=node('article',undefined,'attempt-checks');row.append(node('h5',item.requirement),node('strong',({met:'Visually met',missing:'Missing',uncertain:'Needs verification'})[item.status]),node('p',item.reason));findings.append(row);}
  findings.append(node('h5','Possible regressions'));for(const text of review.findings.regressions)findings.append(node('p',text));if(!review.findings.regressions.length)findings.append(node('p','None reported by the model. This is not a guarantee.','directory-note'));
  if(stale){findings.append(node('p','Run a new review before relying on these findings.','availability-note'));return;}
  findings.append(node('p','Inspect the images and verify uncertain items with the recorded checks. Final acceptance remains in the tested review below.','directory-note'));
  if(review.inspected_at)findings.append(node('p','You marked these findings inspected at '+new Date(review.inspected_at).toLocaleString()+'. This did not accept the task.'));
  else {const inspected=node('button','Mark findings inspected');inspected.type='button';inspected.disabled=busy;inspected.onclick=async()=>{try{valid();const saved=await invoke('task_screenshots',{request:{...request,operation:'save_review',review:{...review,inspected_at:new Date().toISOString()}}});if(taskCurrent())onSaved(saved);}catch(e){status.textContent=String(e.message||e);}};findings.append(inspected);}
 }
 evidenceSelect.onchange=draw;
 run.onclick=async()=>{if(busy)return;try{valid();const captured=basis();const prompt=reviewPrompt(task.criteria,evidence());busy=true;requestId='visual-'+crypto.randomUUID();cancel.disabled=false;draw();status.textContent='Reviewing the two images…';const chosen={...selectedSettings(),model:model.value};if(chosen.model)await invoke('bot_configure',{settings:{provider:provider.value,model:chosen.model,endpoint:chosen.endpoint}});valid();const reply=await invoke('bot_chat',{turn:{provider:provider.value,effort:provider.value==='claude'?(effort.value||null):null,request_id:requestId,visual_review:{...request,before:captured.before,after:captured.after},messages:[{role:'user',content:prompt}],context:{},bot_instructions:'You are a visual reviewer. Follow the comparison request. Return findings only; propose no actions.'}});valid();if(!sameBasis(captured,basis()))throw Error('Images or evidence changed during review. Run a new review.');if(reply.actions?.length)throw Error('Provider returned actions instead of a visual review. Nothing was applied.');const review={basis:captured,provider:provider.value,model:reply.model,at:new Date().toISOString(),findings:parseFindings(reply.text,task.criteria)};const saved=await invoke('task_screenshots',{request:{...request,operation:'save_review',review}});if(taskCurrent()){onSaved(saved);status.textContent='Review saved. Inspect the findings; nothing has been accepted.';}}catch(e){if(panel.isConnected)status.textContent=String(e.message||e);}finally{busy=false;draw();}};
 async function load(){
  evidenceSelect.append(node('option','No tested result linked'));evidenceSelect.options[0].value='0';
  const attempts=Object.values(current()?.frame?.projection?.development_attempts||{}).filter(a=>a.task_ref===task.id&&a.task_revision===task.revision);
  for(const a of attempts){
   const runs=Object.values(a.test_runs||{});for(const r of runs){if(!r.outcome?.snapshot_sha256)continue;const e={attempt:a.id,attempt_revision:a.revision,test_runs_identity:runIdentity(a.test_runs),label:`${a.id} · ${r.profile||'checks'} · ${r.outcome.verdict||r.state}`,run:r.run_id,snapshot:r.outcome.snapshot_sha256,checks:runs.map(x=>({run:x.run_id,profile:x.profile,state:x.state,outcome:x.outcome?.verdict,snapshot:x.outcome?.snapshot_sha256})),capture:'manual-unverified'};choices.push(e);const o=node('option',e.label);o.value=String(choices.length-1);evidenceSelect.append(o);}
   if(a.acceptance){try{const result=await invoke('review_tests',{request:{operation:'list_builds',world:request.world,attempt_ref:a.id}});for(const b of result.builds||[]){if(b.state!=='completed'||!b.artifact_available||b.result?.snapshot_sha256!==a.acceptance.snapshot_sha256)continue;const e={attempt:a.id,attempt_revision:a.revision,test_runs_identity:runIdentity(a.test_runs),label:`${a.id} · build ${b.build_id}`,build:b.build_id,snapshot:b.result.snapshot_sha256,executable:b.result.artifact.sha256,checks:runs.map(x=>({run:x.run_id,profile:x.profile,state:x.state,outcome:x.outcome?.verdict,snapshot:x.outcome?.snapshot_sha256})),capture:'manual-unverified'};choices.push(e);const o=node('option',e.label);o.value=String(choices.length-1);evidenceSelect.append(o);}}catch{status.textContent='Build history unavailable. Recorded checks remain selectable.';}}
  }
  const saved=getRecord().review?.basis.evidence,index=choices.findIndex(e=>sameBasis(e,saved));evidenceSelect.value=String(Math.max(index,0));draw();
 }
 models();load();return {panel,refresh:draw};
}
