/* release-scope — ONE declaration of what a release contains.

   **A RELEASE MEASUREMENT MUST QUANTIFY THE SAME ARTIFACT SET THE RECEIPT
   BINDS.** W.1.4.1 is the argument, and it is a good one because nothing
   about it looked wrong.

   That receipt recorded `113 text assets`. The archive it binds contains
   112. Neither number was typed by a human — the whole point of
   `emit-measurements.mjs` is that they cannot be — and both were produced
   by the same tool on the same tree within the same minute. The gap is
   entirely in WHEN and OVER WHAT:

     release.sh  stage 3   check-source-hygiene   counts the WORKING TREE
                 stage 27  rm -f and-super-rev-*  deletes the previous
                                                  round's sibling receipt
                 stage 28  package                counts nothing; ships
                                                  what is left

   W.1.4 shipped immediately before W.1.4.1, so `and-super-rev-w14.receipt.json`
   was sitting in the tree at stage 3. It is a `.json`, so hygiene counted it;
   it is a release artifact, so stage 27 deleted it; and the ZIP that stage 28
   produced therefore contains one fewer text asset than the receipt describing
   that ZIP says it does. Reproduced deterministically: clean artifact 112, add
   one old sibling receipt 113, remove it 112.

   The figure was machine-generated, bound to a hash, and describing a
   different set of bytes than the ones it was bound to. That is a subtler
   failure than the transcription drift this arc started with, and it is the
   artifact-level sibling of W.1.4.1's own law: a property established at one
   layer gets lost crossing the next boundary.

   So the universe is declared ONCE, here, and everything that needs it
   derives from this file:

     check-source-hygiene.mjs   measures `counted(root)`
     release.sh packager        ships `shipped(root)`
     release.sh replay          re-derives both FROM THE PRODUCED ARCHIVE
                                and refuses if they disagree

   Before this file there were four disagreeing definitions — the hygiene
   walker's basename skip-list, the `zip` packager's `-x` globs, the `python`
   packager's path-prefix tuple, and `.gitignore` — and no two of them
   described the same set. The replay is what makes this file load-bearing
   rather than merely tidy: agreement is PROVEN against the shipped bytes,
   not argued from two walkers that probably enumerate the same things.   */

import { readdirSync, statSync, readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

/* RUNTIME STATE AND BUILD OUTPUT. Excluded from the artifact entirely.

   `ampd/priv/data*` is the original entry and carries the original lesson:
   counting it made hygiene report 110 in a working tree and 108 in the
   shipped bundle, because it exists only after the suite has run. A figure
   that depends on the observer's history is not a property of the release.

   `erl_crash.dump` is the same class and was found by this round. The tree
   carried a 5,066,337-byte dump from a BEAM that died during boot on
   2026-08-22, and every release shipped it: it is 40% of the compressed
   archive, it is named in the repo's own `.gitignore` as "not history worth
   carrying", and no gate had ever looked at it — `.dump` matches no textual
   extension, so hygiene never saw it, and neither packager's skip-list
   mentioned it. A release that ships five megabytes nothing measured is
   making a claim about bytes it never read.

   `deps` and `node_modules` were skipped by the hygiene walker and NOT by
   either packager. `ampd/deps` happens to be absent, so the divergence has
   never fired; one `mix deps.get` before a release is all it would take. */
/* `gen` is W.2's entry, and it is the `ampd/priv/data` lesson in a second
   language. `tauri-build` regenerates `cockpit/gen/schemas/*.json` — four
   files, ~90 KB — on every build from `tauri.conf.json` and
   `capabilities/`, so a tree that has been built and a tree that has not
   ship different sets. Nothing about it looked like build output: it is
   four JSON files in a directory beside the source, and `.json` is
   textual, so hygiene would have counted them and the packager would have
   shipped them.

   Excluded by name with the reason written down, because *silence in a
   skip-list is not a decision* — which is the sentence `erl_crash.dump`
   earned. */
/* `autogenerated` is W.2.1's entry, and the same reasoning one step on.
   `AppManifest::commands` writes `cockpit/permissions/autogenerated/*.toml`
   at build time from the list in `cockpit/build.rs`. Shipping them would
   put a second copy of that declaration in the artifact, which must then
   agree with the first — and it is build output, so a clone that has not
   been built ships a different set than one that has. */
export const SKIP_DIR = new Set([
  'old_scrap', '_build', 'deps', 'node_modules', 'target', 'gen', 'autogenerated',
  '.git', '.elixir_ls', 'data', 'data-elsewhere',
]);

/* Excluded by name wherever they appear. */
export const SKIP_FILE = new Set(['erl_crash.dump']);

/* Build products and previous artifacts. `.zip` matters because the artifact
   is written INTO the tree it packages, so without it each release would
   nest every previous one inside itself; `.orig` is a sabotage backup, which
   `release.sh` refuses outright before it gets here. */
export const SKIP_EXT = ['.so', '.zip', '.orig'];

/* Previous rounds' sibling receipts. **These are the W.1.4.1 defect.** They
   are excluded from the scope rather than merely deleted early, because
   deleting early fixes the ordering and this fixes the CLASS: a receipt that
   arrives in the tree by any route — a hand-run probe, an interrupted round,
   a copy made to compare two revisions — can no longer move a figure. */
export const RECEIPT_RE = /^and-super-rev-[a-z0-9]+\.receipt\.json$/;

/* Textual: NUL-scanned AND counted. ONE set, so there is no gap between
   "what the gate counts" and "what the gate protects".

   W.1.4.1 had a gap in both directions. `site/preview/preview-meta.json`
   shipped and was excluded from hygiene (the walker skipped every directory
   named `preview`); `ampd/c_src/ampd_fd_nif.c` and `host/Cargo.lock` shipped
   and matched no extension. So the gate whose stated purpose is "no NUL in
   any text asset" was blind to the twelve lines of C that `release.sh`
   explicitly ships to be compiled at the far end. `.c`, `.h` and `.lock` are
   here for that reason. */
export const TEXT =
  /\.(html|js|mjs|cjs|json|md|sh|py|ex|exs|rs|toml|txt|css|svg|yml|yaml|c|h|lock)$/;

/* Genuinely opaque. Shipped, never NUL-scanned, and listed so that "we did
   not read these" is a statement in the source rather than an omission. */
export const OPAQUE =
  /\.(png|jpe?g|gif|ico|webp|woff2?|pdf|dump|beam|ez)$/;

function skipEntry(name) {
  if (name.startsWith('.') && name !== '.gitignore') return true;
  if (SKIP_FILE.has(name)) return true;
  if (RECEIPT_RE.test(name)) return true;
  return SKIP_EXT.some(e => name.endsWith(e));
}

/* Every file the release contains, relative to `root`, sorted.
   The packager writes exactly this; the replay checks the archive against
   exactly this. Sorted because a ZIP whose entry order depends on readdir
   order is a different byte history for the same content. */
export function shipped(root) {
  const out = [];
  (function walk(dir, rel) {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      if (e.name.startsWith('.') && e.name !== '.gitignore') continue;
      const abs = dir + '/' + e.name;
      const r = rel ? rel + '/' + e.name : e.name;
      if (e.isDirectory()) { if (!SKIP_DIR.has(e.name)) walk(abs, r); continue; }
      if (skipEntry(e.name)) continue;
      /* An empty file has no bytes to be wrong about, and counting it made
         the figure depend on whether a generator had run yet. */
      if (statSync(abs).size === 0) continue;
      out.push(r);
    }
  })(root, '');
  return out.sort();
}

/* The counted, NUL-scanned subset. `source_text_assets` is exactly this
   length — the name says which universe it is, which is the thing the old
   `text_assets` did not say. */
export function counted(root) {
  return shipped(root).filter(p => TEXT.test(p));
}

/* Shipped and deliberately not read. Returned so a caller can report the
   number instead of leaving it implicit; an unnamed number is the one that
   drifts. */
export function opaque(root) {
  return shipped(root).filter(p => !TEXT.test(p));
}

/* A shipped file that is neither textual nor declared-opaque is a file this
   declaration has no opinion about, and silence is how five megabytes of
   crash dump rode along for four revisions. */
export function undeclared(root) {
  return shipped(root).filter(p => !TEXT.test(p) && !OPAQUE.test(p));
}

/* ── W.1.4.3 · A MEASUREMENT IS EVIDENCE ABOUT BYTES, NOT NAMES ──────────

   W.1.4.2's replay proved a SET property and its receipt claimed a BYTE
   property. Two archives were built to show the gap, both of which it
   accepted:

     A   the same archive with `site/preview/hero-light-preview.png`
         removed. Accepted, because the replay derived the expected file
         list by walking the EXTRACTED ARCHIVE — so a file absent from the
         archive could never appear in the list of files the archive was
         missing. That branch was dead code by construction.

     B   the same paths, the same count, no NUL, and one line of
         `site/app-prototype.html` reverted to a known-bad
         `stabilityToken` that returns the view clock instead of the
         projection digest. Accepted. Running that archive's OWN
         `authority-battery.mjs` against its OWN bytes fails six of its
         assertions — beside a receipt recording zero failures.

   So the ladder of this arc is three rungs, each subtler than the last:

     W.1.3.x   a human copied the wrong measurement
     W.1.4.1   a machine measured the wrong file SET
     W.1.4.2   the file set and count matched and the BYTES differed

   The law:

     **Every release measurement must remain bound to the exact bytes whose
     behaviour produced it.**

   This is why a content digest beats re-running the suites after packaging.
   Re-running the four-and-a-half-minute BEAM battery from the extracted
   archive would prove the archive passes; proving

       bytes the gates tested == bytes handed to the packager
                              == bytes inside the final ZIP

   keeps every behavioural measurement attached to the exact code that
   produced it, for the cost of one hash.

   The digest is over CONTENT, never over ZIP metadata: entry order,
   timestamps, compression method and permissions are all excluded by
   construction, so it stays meaningful even though the archive itself is
   not byte-reproducible. */

export function contentManifest(root) {
  return shipped(root).map(rel => {
    const buf = readFileSync(root + '/' + rel);
    return { path: rel, size: buf.length,
             sha256: createHash('sha256').update(buf).digest('hex') };
  });
}

/* The canonical serialisation. Sorted by path in ONE place — here — so the
   tree side and the archive side cannot disagree by sorting in different
   languages with different collation. */
export function serializeManifest(entries) {
  return [...entries]
    .sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))
    .map(e => `${e.sha256}\t${e.size}\t${e.path}`)
    .join('\n') + '\n';
}

export function digestOf(entries) {
  return createHash('sha256').update(serializeManifest(entries)).digest('hex');
}

export function contentDigest(root) {
  return digestOf(contentManifest(root));
}
