import {createServer} from 'node:http';
import {open} from './lib/cockpit-control.mjs';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,mkdtempSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
const port=Number(process.env.APP_SMOKE_PORT||4797),out=process.env.SUPER_VISUAL_EVIDENCE_DIR||'/home/travis/Documents/Codex/2026-09-12/le/outputs/schematics';
mkdirSync(out,{recursive:true});let app;const checks=[];
const check=(name,value)=>{assert.ok(value,name);checks.push(name);console.log(name);};
try{
 app=await open({port,fixture:true});
 check('Continue work is the initial screen',await app.page(`return !document.querySelector('#work-focus').hidden && !!document.querySelector('#focus-home') && document.querySelectorAll('[data-screen=continue-work]').length===1`));
 const ws=await app.create('open_workspace',{name:'Focus fixture'},{kind:'workspaces',field:'name',value:'Focus fixture'});
 const goal=await app.create('open_goal',{workspace_ref:ws.record.id,title:'Finish a clear next step'},{kind:'goals',field:'title',value:'Finish a clear next step'});
 const bot=await app.create('register_bot',{client_ref:'focus-fixture',workspace_ref:ws.record.id,name:'Focus builder',role:'Builder',group:'Tests',provider:'claude',instructions:'Fixture'},{kind:'bots',field:'client_ref',value:'focus-fixture'});
 const folder=mkdtempSync((process.env.DEVELOPMENT_TEST_ROOT||'/tmp')+'/focus-repo-');execFileSync('git',['init','-q',folder]);
 await app.page(`document.querySelector('[data-nav="repositories"]').click();document.querySelector('[data-host-action="choose-repository"]').click()`);
 await new Promise(r=>setTimeout(r,800));execFileSync('/usr/bin/python3',['tools/development-confirm-folder.py',String(process.pid),folder],{env:{...process.env,SUPER_CHOOSER_TITLE:'Register a local Git repository'}});
 const repo=await app.until(async()=>(await app.list('repositories'))[0],10000,'repository');
 await app.intent('open_lane',{goal_ref:goal.record.id,actor:bot.record.actor,repository_ref:repo.ref||repo.id,base_revision:'HEAD'});
 const lane=await app.until(async()=>(await app.list('lanes')).find(l=>l.actor===bot.record.actor),10000,'lane');
 for(const n of [1,2])await app.intent('create_development_task',{client_ref:'focus-'+n,lane_ref:lane.id,title:'Focused step '+n,criteria:'One reviewed change. '.repeat(30)});
 const tasks=await app.until(async()=>{const t=(await app.list('development_tasks')).filter(t=>t.client_ref?.startsWith('focus-'));return t.length===2&&t;},10000,'plans');
 await app.page(`document.dispatchEvent(new CustomEvent('focus-development-task',{detail:{taskId:arguments[0]}}))`,[tasks[1].id]);
 check('Chosen plan has one primary next action and a collapsed queue',await app.page(`return document.querySelector('[data-focus-task]').dataset.focusTask===arguments[0] && document.querySelectorAll('#work-focus .focus-card .primary').length===1 && !document.querySelector('.focus-queue').open`,[tasks[1].id]));
 await fetch(`http://127.0.0.1:${port}/session/${app.session()}/window/rect`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({width:1080,height:620})});
 check('Next action stays visible above long collapsed criteria',await app.page(`const b=document.querySelector('#focus-next').getBoundingClientRect();return b.top>=0 && b.bottom<=innerHeight && document.querySelector('.focus-criteria').tagName==='DETAILS' && !document.querySelector('.focus-criteria').open`));
 await app.page(`document.querySelector('#focus-next').click()`);
 check('Prepare action opens Editor with the selected plan',await app.page(`return !document.querySelector('[data-screen=editor]').hidden && document.querySelector('#editor-task-context').textContent.includes('Focused step 2')`));
 await app.page(`document.querySelector('#focus-home').click()`);
 check('Continue work returns to the same plan',await app.page(`return !document.querySelector('#work-focus').hidden && document.querySelector('[data-focus-task]').dataset.focusTask===arguments[0]`,[tasks[1].id]));
 await app.page(`const id=arguments[0];import('./task-session.js').then(m=>{const w=window.cockpit.frame.world,world=JSON.stringify([w.world_incarnation,w.world_generation,w.projection_epoch]);m.publishTaskSession({botId:'focus-fixture',world,reply:'Waiting for reply',tasks:[{id,revision:1,world}]});})`,[tasks[1].id]);
 await app.until(()=>app.page(`return document.querySelector('#focus-next').textContent==='Watch bot'`),10000,'live guidance');
 check('The focused task shows the matching live reply step',await app.page(`return document.querySelector('#work-focus [aria-current=step]').textContent==='Bot reply'`));
 await app.page(`const id=arguments[0];import('./task-session.js').then(m=>{const w=window.cockpit.frame.world,world=JSON.stringify([w.world_incarnation,w.world_generation,w.projection_epoch]);m.publishTaskSession({botId:'focus-fixture',world,reply:'Reply received',tasks:[{id,revision:1,world}]});})`,[tasks[1].id]);
 await app.until(()=>app.page(`return document.querySelector('#work-focus [aria-current=step]').textContent==='Review'`),10000,'review guidance');
 check('A reply offers review without marking the task finished',(await app.list('development_tasks')).find(t=>t.id===tasks[1].id).status==='planned');
 await app.page(`location.reload()`);
 await app.until(()=>app.page(`return document.querySelector('[data-focus-task]')?.dataset.focusTask===arguments[0]`,[tasks[1].id]),20000,'restored focus');
 check('Reload restores the chosen task without sending a request',await app.page(`return !document.querySelector('#work-focus').hidden && document.querySelector('#focus-current').textContent==='Prepare source files'`));
 const shot=async(name)=>{const response=await fetch(`http://127.0.0.1:${port}/session/${app.session()}/screenshot`);writeFileSync(`${out}/${name}.png`,Buffer.from((await response.json()).value,'base64'));};
 await fetch(`http://127.0.0.1:${port}/session/${app.session()}/window/rect`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({width:1440,height:980})});
 await app.page(`document.querySelector('#toggle-schematics').click();document.querySelector('[data-schematic-node=task]').click()`);
 check('Schematics toggles into the selected task with a pinned inspector',await app.page(`return !document.querySelector('#schematics').hidden && document.querySelector('.schematic-inspector').textContent.includes('Focused step 2') && document.querySelector('#toggle-schematics').getAttribute('aria-pressed')==='true'`));
 await shot('01_Current_Task');
 await app.page(`document.querySelector('[data-schematic-level=connections]').click();document.querySelector('[data-schematic-node=development-tasks]').click()`);
 check('Connections offer a real destination and describe the link',await app.page(`return !!document.querySelector('[data-schematic-open=development-tasks]') && document.querySelector('.schematic-inspector').textContent.includes('focuses a plan')`));
 await shot('02_Screen_Connections');
 await app.page(`document.querySelector('[data-schematic-level=app]').click()`);
 check('Whole app includes all registered screens',await app.page(`return document.querySelectorAll('[data-schematic-node]').length===28`));
 await shot('03_Whole_App');
 await app.page(`document.querySelector('#toggle-schematics').click();document.querySelector('[data-nav=new-workspace]').click();const input=document.querySelector('[data-draft=workspace_name]');input.value='Keep this unsaved draft';input.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#toggle-schematics').click();document.querySelector('[data-schematic-level=screen]').click();document.querySelector('#toggle-schematics').click()`);
 check('Toggling preserves the current page and unsaved input',await app.page(`return !document.querySelector('[data-screen=new-workspace]').hidden && document.querySelector('[data-draft=workspace_name]').value==='Keep this unsaved draft'`));
 await app.page(`document.querySelector('#focus-home').click();document.querySelector('#toggle-schematics').click()`);
 await fetch(`http://127.0.0.1:${port}/session/${app.session()}/window/rect`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({width:1080,height:620})});
 await new Promise(r=>setTimeout(r,250));
 check('Small window retains toggle and inspector without horizontal page overflow',await app.page(`const b=document.querySelector('#toggle-schematics').getBoundingClientRect();return b.right<=innerWidth && b.top>=0 && document.querySelector('#workspace-canvas').scrollWidth<=document.querySelector('#workspace-canvas').clientWidth+2`));
 await shot('04_Small_Window');
 await app.page(`document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))`);
 check('Escape returns to the same selected task',await app.page(`return document.querySelector('#schematics').hidden && document.querySelector('[data-focus-task]').dataset.focusTask===arguments[0]`,[tasks[1].id]));
 await app.page(`import('./app-shell.js').then(m=>{window.schematicPages=m.screens.map(s=>s[0]);window.schematicNavigate=m.navigate;})`);
 await app.until(()=>app.page(`return !!window.schematicPages`),10000,'screen registry');
 for(const id of await app.page(`return window.schematicPages`)){await app.page(`window.schematicNavigate(arguments[0]);if(document.querySelector('#schematics').hidden)document.querySelector('#toggle-schematics').click()`,[id]);assert.ok(await app.page(`return !document.querySelector('#schematics').hidden && !!document.querySelector('[data-schematic-node]')`),id);}
 check('Every registered screen has a schematic counterpart',true);
 const server=createServer((req,res)=>res.end('<body style="background:red"><h1>Native preview fixture</h1></body>'));await new Promise(r=>server.listen(0,'127.0.0.1',r));
 try{
 await app.page(`document.querySelector('#toggle-schematics').click();window.schematicNavigate('browser');document.querySelector('#browser-url').value=arguments[0];document.querySelector('#browser-go').click()`,['http://127.0.0.1:'+server.address().port]);
 await app.until(async()=>((await app.native('browser_surface',{action:'status'})).tabs??[]).length>0,10000,'native preview');
 await app.page(`document.querySelector('#toggle-schematics').click()`);await new Promise(r=>setTimeout(r,500));
 execFileSync('/usr/bin/python3',['tools/development-capture-window.py',String(process.pid),`${out}/05_Browser_Cover.png`]);
 check('Browser schematic opens while the native preview remains retained',await app.page(`return !document.querySelector('#schematics').hidden && document.querySelector('#schematics h1').textContent.includes('Browser')`));
 await app.page(`document.querySelector('#toggle-schematics').click()`);
 check('Leaving the schematic restores the Browser page',await app.page(`return !document.querySelector('[data-screen=browser]').hidden`));
 await app.native('browser_surface',{action:'close'});
 }finally{server.close();}
 writeFileSync(`${out}/checks.json`,JSON.stringify({passed:true,checks},null,2));
}finally{if(app)await app.close();}
