import {createServer} from 'node:http';
import {open} from './lib/cockpit-control.mjs';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,mkdtempSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
const port=Number(process.env.APP_SMOKE_PORT||4797),out=process.env.SUPER_VISUAL_EVIDENCE_DIR||'/home/travis/Documents/Codex/2026-09-12/le/outputs/schematics-4';
mkdirSync(out,{recursive:true});let app;const checks=[];
const ready=()=>app.until(()=>app.page(`return !document.querySelector('#schematics').hidden&&!document.querySelector('.schematic-note').hasAttribute('aria-busy')&&!!document.querySelector('[data-schematic-node]')`),20000,'layout ready');
const check=(name,value)=>{assert.ok(value,name);checks.push(name);console.log(name);};
try{
 app=await open({port,fixture:true});
 check('Continue work is the initial screen',await app.page(`return !document.querySelector('#work-focus').hidden && !!document.querySelector('#focus-home') && document.querySelectorAll('[data-screen=continue-work]').length===1`));
 const ws=await app.create('open_workspace',{name:'Focus fixture'},{kind:'workspaces',field:'name',value:'Focus fixture'});
 const goal=await app.create('open_goal',{workspace_ref:ws.record.id,title:'Finish a clear next step'},{kind:'goals',field:'title',value:'Finish a clear next step'});
 const bot=await app.create('register_bot',{client_ref:'focus-fixture',workspace_ref:ws.record.id,name:'Focus builder',role:'Builder',group:'Tests',provider:'claude',instructions:'Fixture'},{kind:'bots',field:'client_ref',value:'focus-fixture'});
 const folder=mkdtempSync((process.env.DEVELOPMENT_TEST_ROOT||'/tmp')+'/focus-repo-');execFileSync('git',['init','-q',folder]);writeFileSync(folder+'/sample.txt','A real Editor fixture.');execFileSync('git',['-C',folder,'add','sample.txt']);execFileSync('git',['-C',folder,'-c','user.name=Super fixture','-c','user.email=fixture@example.invalid','commit','-qm','Initial source']);
 await app.page(`document.querySelector('[data-nav="repositories"]').click();document.querySelector('[data-host-action="choose-repository"]').click()`);
 await new Promise(r=>setTimeout(r,800));execFileSync('/usr/bin/python3',['tools/development-confirm-folder.py',String(process.pid),folder],{env:{...process.env,SUPER_CHOOSER_TITLE:'Register a local Git repository'}});
 const repo=await app.until(async()=>(await app.list('repositories'))[0],10000,'repository');
 await app.intent('open_lane',{goal_ref:goal.record.id,actor:bot.record.actor,repository_ref:repo.ref||repo.id,base_revision:'HEAD'});
 const lane=await app.until(async()=>(await app.list('lanes')).find(l=>l.actor===bot.record.actor),10000,'lane');
 for(const n of [1,2])await app.intent('create_development_task',{client_ref:'focus-'+n,lane_ref:lane.id,title:'Focused step '+n,criteria:'One reviewed change. '.repeat(30)});
 await app.intent('open_worker',{locus_ref:lane.id,purpose:'Idle worker for responsiveness'});
 const tasks=await app.until(async()=>{const t=(await app.list('development_tasks')).filter(t=>t.client_ref?.startsWith('focus-'));return t.length===2&&t;},10000,'plans');
 await app.page(`document.dispatchEvent(new CustomEvent('focus-development-task',{detail:{taskId:arguments[0]}}))`,[tasks[1].id]);
 check('Chosen plan has one primary next action and a collapsed queue',await app.page(`return document.querySelector('[data-focus-task]').dataset.focusTask===arguments[0] && document.querySelectorAll('#work-focus .focus-card .primary').length===1 && !document.querySelector('.focus-queue').open`,[tasks[1].id]));
 await fetch(`http://127.0.0.1:${port}/session/${app.session()}/window/rect`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({width:1080,height:620})});
 check('Next action stays visible above long collapsed criteria',await app.page(`const b=document.querySelector('#focus-next').getBoundingClientRect();return b.top>=0 && b.bottom<=innerHeight && document.querySelector('.focus-criteria').tagName==='DETAILS' && !document.querySelector('.focus-criteria').open`));
 await app.page(`document.querySelector('#focus-next').click()`);
 check('Prepare action opens Editor with the selected plan',await app.page(`return !document.querySelector('[data-screen=editor]').hidden && document.querySelector('#editor-task-context').textContent.includes('Focused step 2')`));
 await app.page(`document.querySelector('#focus-home').click()`);
 check('Continue work returns to the same plan',await app.page(`return !document.querySelector('#work-focus').hidden && document.querySelector('[data-focus-task]').dataset.focusTask===arguments[0]`,[tasks[1].id]));
 await app.page(`const id=arguments[0];import('./task-session.js').then(m=>{const w=window.cockpit.frame.world,world=JSON.stringify([w.world_incarnation,w.world_generation,w.projection_epoch]);m.publishTaskSession({botId:'focus-fixture',world,reply:'Waiting for reply',tasks:[{id,revision:1,world}]});})`,[tasks[1].id]);
 await app.until(()=>app.page(`return document.querySelector('#focus-next').textContent==='Watch bot'`),10000,'live guidance');
 check('The focused task shows the matching live reply step',await app.page(`return document.querySelector('#work-focus [aria-current=step]').textContent==='Bot reply'`));
 await app.page(`const id=arguments[0];import('./task-session.js').then(m=>{const w=window.cockpit.frame.world,world=JSON.stringify([w.world_incarnation,w.world_generation,w.projection_epoch]);m.publishTaskSession({botId:'focus-fixture',world,reply:'Reply received',tasks:[{id,revision:1,world}]});})`,[tasks[1].id]);
 await app.until(()=>app.page(`return document.querySelector('#work-focus [aria-current=step]').textContent==='Review'`),10000,'review guidance');
 check('A reply offers review without marking the task finished',(await app.list('development_tasks')).find(t=>t.id===tasks[1].id).status==='planned');
 await app.page(`location.reload()`);
 await app.until(()=>app.page(`return document.querySelector('[data-focus-task]')?.dataset.focusTask===arguments[0]`,[tasks[1].id]),20000,'restored focus');
 check('Reload restores the chosen task without sending a request',await app.page(`return !document.querySelector('#work-focus').hidden && document.querySelector('#focus-current').textContent==='Prepare source files'`));
 const shot=async(name)=>{const response=await fetch(`http://127.0.0.1:${port}/session/${app.session()}/screenshot`);writeFileSync(`${out}/${name}.png`,Buffer.from((await response.json()).value,'base64'));};
 await fetch(`http://127.0.0.1:${port}/session/${app.session()}/window/rect`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({width:1440,height:980})});
 const idleBefore=await app.page(`return {frames:window.cockpit.frames,refusals:window.cockpit.frame.projection.recent_refusals}`);
 await new Promise(r=>setTimeout(r,2000));
 check('Idle workers do not generate refusal or full-frame refresh loops',await app.page(`return window.cockpit.frames-arguments[0].frames<=2&&JSON.stringify(window.cockpit.frame.projection.recent_refusals)===JSON.stringify(arguments[0].refusals)`,[idleBefore]));
 const toggleRect=await app.page(`const b=document.querySelector('#toggle-schematics').getBoundingClientRect();return {x:Math.round(b.x+b.width/2),y:Math.round(b.y+b.height/2)}`);
 const realClick=await fetch(`http://127.0.0.1:${port}/session/${app.session()}/actions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({actions:[{type:'pointer',id:'mouse',parameters:{pointerType:'mouse'},actions:[{type:'pointerMove',duration:0,...toggleRect},{type:'pointerDown',button:0},{type:'pause',duration:150},{type:'pointerUp',button:0}]}]})});
 assert.ok(realClick.ok,await realClick.text());await ready();
 check('A normal-duration pointer click opens Schematics',await app.page(`return !document.querySelector('#schematics').hidden`));
 await app.page(`document.querySelector('[data-schematic-node=task]').click()`);
 check('Schematics toggles into the selected task with a pinned inspector',await app.page(`return !document.querySelector('#schematics').hidden && document.querySelector('.schematic-inspector').textContent.includes('Focused step 2') && document.querySelector('#toggle-schematics').getAttribute('aria-pressed')==='true'`));
 check('Graph fills the entire workspace below the app header',await app.page(`const v=document.querySelector('.schematic-viewport').getBoundingClientRect(),c=document.querySelector('#workspace-canvas').getBoundingClientRect(),h=document.querySelector('#topbar').getBoundingClientRect();return Math.abs(v.left)<2&&Math.abs(v.right-innerWidth)<2&&Math.abs(v.top-h.bottom)<2&&Math.abs(v.bottom-innerHeight)<2&&v.width===c.width&&v.height===c.height`));
 await app.page(`document.querySelector('[data-schematic-zoom=all]').click()`);
 check('Fit diagram leaves nodes clear of floating controls and details',await app.page(`const b=document.querySelector('.schematic-board').getBoundingClientRect(),h=document.querySelector('.schematic-heading').getBoundingClientRect(),i=document.querySelector('.schematic-inspector').getBoundingClientRect(),z=document.querySelector('.schematic-zoom').getBoundingClientRect();return b.top>=h.bottom&&b.right<=i.left&&b.bottom<=z.top`));
 await shot('01_Current_Task');
 await app.page(`document.querySelector('[data-schematic-zoom=reset]').click()`);
 await app.page(`document.querySelector('[data-schematic-follow=bot]').click();document.querySelector('[data-schematic-zoom=out]').click();document.querySelector('[data-schematic-zoom=out]').click()`);
 check('Following a connection selects its node and highlights only neighboring wires',await app.page(`return document.querySelector('[data-schematic-node=bot]').getAttribute('aria-pressed')==='true'&&document.querySelectorAll('path.schematic-traced').length===4 && !!document.querySelector('path.schematic-muted')`));
 check('Zoom scales the diagram without changing the selected component',await app.page(`return document.querySelector('#schematic-zoom-label').textContent==='80%' && document.querySelector('.schematic-inspector h2').textContent==='Focus builder'`));
 await shot('07_Trace_And_Zoom');
 await app.page(`document.querySelector('[data-schematic-direction=RIGHT]').click()`);await ready();
 check('Flow direction changes while preserving the selected component',await app.page(`return document.querySelector('[data-schematic-direction=RIGHT]').getAttribute('aria-pressed')==='true'&&document.querySelector('[data-schematic-node=bot]').getAttribute('aria-pressed')==='true'`));
 await app.page(`document.querySelector('[data-schematic-zoom=all]').click()`);
 check('Fit diagram keeps the whole routed graph inside the viewport',await app.page(`const b=document.querySelector('.schematic-board').getBoundingClientRect(),v=document.querySelector('.schematic-viewport').getBoundingClientRect();return b.width<=v.width+2&&b.height<=v.height+2`));
 await shot('11_Rightward_Flow');
 await app.page(`document.querySelector('[data-schematic-zoom=reset]').click()`);

 await app.page(`document.querySelector('[data-schematic-direction=DOWN]').click();document.querySelector('#toggle-schematics').click();document.querySelector('#toggle-schematics').click()`);await ready();
 check('Rapid direction changes and toggles cannot restore a stale layout',await app.page(`return document.querySelector('[data-schematic-direction=DOWN]').getAttribute('aria-pressed')==='true'&&document.querySelector('[data-schematic-node=bot]').getAttribute('aria-pressed')==='true'`));

 await app.page(`document.querySelector('[data-schematic-direction=DOWN]').click()`);await ready();

 await app.page(`document.querySelector('#schematic-clear-trace').click()`);
 check('Clear trace restores every node and connection',await app.page(`return !document.querySelector('.schematic-traced')&&!document.querySelector('.schematic-muted')`));
 await app.page(`document.querySelector('[data-schematic-zoom=fit]').click();document.querySelector('[data-schematic-zoom=reset]').click()`);

 await app.page(`document.querySelector('[data-schematic-level=connections]').click()`);await ready();await app.page(`document.querySelector('[data-schematic-node=development-tasks]').click()`);
 check('Connections offer a real destination and describe the link',await app.page(`return !!document.querySelector('[data-schematic-open=development-tasks]') && document.querySelector('.schematic-inspector').textContent.includes('focuses a plan')`));
 await shot('02_Screen_Connections');
 await app.page(`document.querySelector('[data-schematic-level=app]').click()`);await ready();
 check('Whole app includes all registered screens',await app.page(`return document.querySelectorAll('[data-schematic-node]').length===28`));
 await app.page(`document.querySelector('[data-schematic-zoom=all]').click()`);
 await shot('03_Whole_App');
 await app.page(`document.querySelector('[data-schematic-zoom=reset]').click()`);
 await app.page(`document.querySelector('#toggle-schematics').click();document.querySelector('[data-nav=new-workspace]').click();const input=document.querySelector('[data-draft=workspace_name]');input.value='Keep this unsaved draft';input.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#toggle-schematics').click();document.querySelector('[data-schematic-level=screen]').click();document.querySelector('#toggle-schematics').click()`);
 check('Toggling preserves the current page and unsaved input',await app.page(`return !document.querySelector('[data-screen=new-workspace]').hidden && document.querySelector('[data-draft=workspace_name]').value==='Keep this unsaved draft'`));
 await app.page(`document.querySelector('#focus-home').click();document.querySelector('#toggle-schematics').click()`);
 await fetch(`http://127.0.0.1:${port}/session/${app.session()}/window/rect`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({width:1080,height:620})});
 await new Promise(r=>setTimeout(r,250));
 check('Small window retains toggle and inspector without horizontal page overflow',await app.page(`const b=document.querySelector('#toggle-schematics').getBoundingClientRect();return b.right<=innerWidth && b.top>=0 && document.querySelector('#workspace-canvas').scrollWidth<=document.querySelector('#workspace-canvas').clientWidth+2`));
 await ready();await app.page(`document.querySelector('[data-schematic-node=task]').click();document.querySelector('[data-schematic-zoom=all]').click()`);
 check('Small workspace remains full size with reachable floating panels',await app.page(`const v=document.querySelector('.schematic-viewport').getBoundingClientRect(),i=document.querySelector('.schematic-inspector').getBoundingClientRect(),z=document.querySelector('.schematic-zoom').getBoundingClientRect();return Math.abs(v.bottom-innerHeight)<2&&v.width===innerWidth&&i.bottom<=z.top&&z.bottom<=innerHeight&&z.left>=0`));
 await shot('04_Small_Window');
 await app.page(`document.querySelector('.schematic-inspector-close').click()`);
 check('Hiding details preserves selection and returns keyboard focus to Details',await app.page(`return document.querySelector('.schematic-inspector').hidden&&document.querySelector('[data-schematic-node=task]').getAttribute('aria-pressed')==='true'&&document.activeElement.id==='schematic-details-toggle'`));
 await app.page(`document.querySelector('#schematic-details-toggle').click()`);
 check('Details can be reopened without leaving the canvas',await app.page(`return !document.querySelector('.schematic-inspector').hidden&&document.querySelector('.schematic-inspector h2').textContent==='Focused step 2'`));
 await app.page(`document.querySelector('[data-schematic-zoom=reset]').click();document.querySelector('.schematic-viewport').scrollTo(0,100)`);
 const panStart=await app.page(`return document.querySelector('.schematic-viewport').scrollTop`);
 const drag=await fetch(`http://127.0.0.1:${port}/session/${app.session()}/actions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({actions:[{type:'pointer',id:'mouse',parameters:{pointerType:'mouse'},actions:[{type:'pointerMove',duration:0,x:24,y:340},{type:'pointerDown',button:0},{type:'pointerMove',duration:300,x:24,y:240},{type:'pointerUp',button:0}]}]})});
 assert.ok(drag.ok,await drag.text());
 check('Dragging empty canvas pans the graph without changing the selected node',await app.page(`return document.querySelector('.schematic-viewport').scrollTop>=arguments[0]+90&&document.querySelector('[data-schematic-node=task]').getAttribute('aria-pressed')==='true'`,[panStart]));
 await fetch(`http://127.0.0.1:${port}/session/${app.session()}/window/rect`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({width:720,height:700})});
 await new Promise(r=>setTimeout(r,250));
 check('Narrow window keeps a full canvas and separates the wrapped toolbar from details',await app.page(`const v=document.querySelector('.schematic-viewport').getBoundingClientRect(),h=document.querySelector('.schematic-heading').getBoundingClientRect(),i=document.querySelector('.schematic-inspector').getBoundingClientRect(),z=document.querySelector('.schematic-zoom').getBoundingClientRect();return v.width===innerWidth&&Math.abs(v.bottom-innerHeight)<2&&i.bottom<=z.top&&h.right<=i.left&&z.right<=innerWidth`));
 await shot('12_Narrow_Workspace');
 await app.page(`document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))`);
 check('Escape returns to the same selected task',await app.page(`return document.querySelector('#schematics').hidden && document.querySelector('[data-focus-task]').dataset.focusTask===arguments[0]`,[tasks[1].id]));
 await app.page(`import('./app-shell.js').then(m=>{window.schematicPages=m.screens.map(s=>s[0]);window.schematicNavigate=m.navigate;})`);
 await app.until(()=>app.page(`return !!window.schematicPages`),10000,'screen registry');
 for(const id of await app.page(`return window.schematicPages`)){await app.page(`window.schematicNavigate(arguments[0]);if(document.querySelector('#schematics').hidden)document.querySelector('#toggle-schematics').click()`,[id]);await ready();assert.ok(await app.page(`return !document.querySelector('#schematics').hidden && !!document.querySelector('[data-schematic-node]')`),id);}
 check('Every registered screen has a schematic counterpart',true);
 await fetch(`http://127.0.0.1:${port}/session/${app.session()}/window/rect`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({width:1440,height:980})});
 await app.page(`document.querySelector('#toggle-schematics').click();document.dispatchEvent(new CustomEvent('continue-development-task',{detail:{taskId:arguments[0]}}));document.querySelector('#development-choose-editor').click()`,[tasks[1].id]);
 await new Promise(r=>setTimeout(r,800));execFileSync('/usr/bin/python3',['tools/development-confirm-folder.py',String(process.pid),folder]);
 await app.until(()=>app.page(`return !!document.querySelector('[data-file-path="sample.txt"]')`),10000,'Editor file');
 await app.page(`document.querySelector('[data-file-path="sample.txt"]').click()`);
 await app.until(()=>app.page(`return !document.querySelector('#editor-discuss').disabled`),10000,'file loaded');
 await app.page(`document.querySelector('#toggle-schematics').click()`);await ready();await app.page(`document.querySelector('[data-schematic-node=tabs]').click()`);
 check('Editor schematic shows the real linked file session',await app.page(`return document.querySelector('[data-schematic-node=tabs] span').textContent==='1 open'&&document.querySelector('.schematic-inspector').textContent.includes('sample.txt')&&document.querySelector('[data-schematic-node=drafts] span').textContent==='No unsaved drafts'`));
 await app.page(`document.querySelector('[data-schematic-zoom=out]').click();document.querySelector('[data-schematic-zoom=out]').click()`);
 await app.page(`document.querySelector('[data-schematic-zoom=all]').click()`);
 await shot('08_Editor_Internals');
 // A local provider fixture exercises actual send/completion wiring. Its
 // controlled observation below stands in for the managed-provider polling payload.
 let heldReply=null,chatCalls=0;
 const providerFixture=createServer((req,res)=>{if(req.url==='/api/tags'){res.setHeader('content-type','application/json');res.end(JSON.stringify({models:[{name:'activity-fixture'}]}));return;}req.resume();req.on('end',()=>{chatCalls++;heldReply=res;});});
 await new Promise(r=>providerFixture.listen(0,'127.0.0.1',r));
 try{
 await app.page(`document.querySelector('#toggle-schematics').click();document.querySelector('#editor-discuss').click()`);
 await app.until(()=>app.page(`return !document.querySelector('#bot-provider').disabled&&document.querySelector('#bot-surface').dataset.screen==='bot:focus-fixture'`),15000,'assigned bot').catch(async e=>{console.log(await app.page(`return {editor:document.querySelector('#editor-status').textContent,bot:document.querySelector('#bot-status').textContent,route:document.querySelector('#bot-surface').dataset.screen}`));throw e;});
 await app.page(`const p=document.querySelector('#bot-provider');p.value='ollama';p.dispatchEvent(new Event('change'))`);
 await app.until(()=>app.page(`return !document.querySelector('#bot-provider').disabled`),15000,'provider selection');
 await app.page(`document.querySelector('#bot-endpoint').value=arguments[0];document.querySelector('#bot-connect').click()`,['http://127.0.0.1:'+providerFixture.address().port]);
 await app.until(()=>app.page(`return !document.querySelector('#bot-send').disabled`),15000,'local fixture ready');
 await app.page(`window.schematicNavigate('editor');document.querySelector('#editor-discuss').click()`);
 await app.until(()=>app.page(`return document.querySelector('#bot-attachment-list').textContent.includes('sample.txt')`),10000,'task file attached');
 await app.page(`document.querySelector('#bot-message').value='Describe this fixture file';document.querySelector('#bot-send').click();document.querySelector('#focus-home').click()`);
 await app.until(async()=>heldReply&&await app.page(`return document.querySelector('#work-focus [data-task-activity]').dataset.phase==='running'`),10000,'request observed');
 check('A real app request appears in Continue work while the provider is still pending',chatCalls===1&&await app.page(`return document.querySelector('#work-focus [data-task-activity]').open&&document.querySelector('#work-focus [data-task-activity]').textContent.includes('Request sent')`));
 await app.page(`import('./task-activity.js').then(m=>{window.taskActivityModule=m;const w=window.cockpit.frame.world,world=JSON.stringify([w.world_incarnation,w.world_generation,w.projection_epoch]),p=window.cockpit.frame.projection;const value=m.taskActivityFor(p,p.development_tasks[arguments[0]],world);window.observedRequest=value.id;m.observeTaskActivity(value.id,{active:true,received_bytes:94,text:'Test provider observation: inspecting sample.txt. A reviewed change will need your approval.'});})`,[tasks[1].id]);
 await app.until(()=>app.page(`return document.querySelector('#work-focus .task-activity-output').textContent.includes('Test provider observation')`),10000,'observed text');
 await shot('13_Task_Activity');
 await app.page(`document.querySelector('#toggle-schematics').click()`);await ready();
 check('Schematics shows matching request text and events without opening the conversation',await app.page(`return document.querySelector('#schematics .task-activity-output').textContent.includes('Test provider observation')&&document.querySelector('#schematics [data-task-activity]').textContent.includes('Assistant text received')`));
 await shot('14_Schematic_Activity');
 await app.page(`window.activityNode=document.querySelector('[data-schematic-node=bot]');window.taskActivityModule.observeTaskActivity(window.observedRequest,{active:true,received_bytes:120,text:'Test provider observation: inspection complete; preparing the answer.'})`);
 check('Incoming text updates keep graph nodes mounted',await app.page(`return window.activityNode===document.querySelector('[data-schematic-node=bot]')&&document.querySelector('#schematics .task-activity-output').textContent.includes('preparing the answer')`));
 heldReply.setHeader('content-type','application/json');heldReply.end(JSON.stringify({message:{role:'assistant',content:'Fixture reply: sample.txt is ready for a reviewed change.'},done:true}));heldReply=null;
 await app.until(()=>app.page(`return document.querySelector('#schematics [data-task-activity]').dataset.phase==='complete'`),10000,'reply complete');
 check('Provider completion updates task activity without applying files',await app.page(`return document.querySelector('#schematics .task-activity-output').textContent.includes('Fixture reply:')&&window.cockpit.frame.projection.development_tasks[arguments[0]].status==='planned'`,[tasks[1].id]));
 await shot('15_Reply_Complete');
 await app.page(`document.querySelector('#toggle-schematics').click();document.dispatchEvent(new CustomEvent('focus-development-task',{detail:{taskId:arguments[0]}}))`,[tasks[0].id]);
 check('A different task cannot display this request or its text',await app.page(`return document.querySelector('#work-focus .task-activity-output').hidden&&document.querySelector('#work-focus [data-task-activity]').textContent.includes('No request observed')`));
 await app.page(`document.dispatchEvent(new CustomEvent('focus-development-task',{detail:{taskId:arguments[0]}}));document.querySelector('#toggle-schematics').click()`,[tasks[1].id]);await ready();
 await app.page(`document.querySelector('#toggle-schematics').click();window.schematicNavigate('editor');document.querySelector('#editor-discuss').click()`);
 await app.until(()=>app.page(`return document.querySelector('#bot-attachment-list').textContent.includes('sample.txt')&&!document.querySelector('#bot-send').disabled`),10000,'fresh task attachment');
 await app.page(`document.querySelector('#bot-message').value='Retryable fixture request';document.querySelector('#bot-send').click();document.querySelector('#focus-home').click()`);
 await app.until(async()=>!!heldReply,10000,'second request');heldReply.statusCode=503;heldReply.end('{}');heldReply=null;
 await app.until(()=>app.page(`return document.querySelector('#work-focus [data-task-activity]').dataset.phase==='stopped'`),10000,'stopped request');
 check('Provider failure stops activity and restores the message without retrying',chatCalls===2&&await app.page(`return document.querySelector('#bot-message').value==='Retryable fixture request'&&document.querySelector('#work-focus [data-task-activity]').textContent.includes('Nothing is resent automatically')`));
 check('Restored attachments retain connection recovery as the primary action',await app.page(`return document.querySelector('#focus-next').textContent==='Check the provider connection'&&document.querySelector('#work-focus [data-task-activity]').textContent.includes('Provider unavailable')`));
 await shot('16_Connection_Recovery');
 await app.page(`document.querySelector('#toggle-schematics').click()`);await ready();
 check('Schematic activity explains the same connection failure',await app.page(`return document.querySelector('#schematics [data-task-activity]').textContent.includes('Provider unavailable')`));
 await app.page(`document.querySelector('#toggle-schematics').click();document.querySelector('#focus-next').click()`);
 check('Recovery opens the assigned conversation with the draft and attachment intact',await app.page(`return !document.querySelector('#bot-surface').hidden&&document.querySelector('#bot-message').value==='Retryable fixture request'&&document.querySelector('#bot-attachment-list').textContent.includes('sample.txt')`));
 await app.page(`document.querySelector('#bot-send').click();document.querySelector('#focus-home').click()`);
 await app.until(async()=>!!heldReply,10000,'explicit retry');heldReply.statusCode=429;heldReply.end('{}');heldReply=null;
 await app.until(()=>app.page(`return document.querySelector('#focus-next').textContent==='Review model availability'`),10000,'capacity guidance');
 check('Capacity failure has a distinct next step and does not disconnect the provider',chatCalls===3&&await app.page(`return document.querySelector('#work-focus [data-task-activity]').textContent.includes('Provider capacity reached')&&!document.querySelector('#bot-send').disabled`));
 await shot('17_Capacity_Recovery');
 await app.page(`document.querySelector('#toggle-schematics').click()`);await ready();
 await shot('18_Schematic_Recovery');
 await app.page(`document.querySelector('#toggle-schematics').click();document.querySelector('#focus-next').click();document.querySelector('#bot-send').click();document.querySelector('#focus-home').click()`);
 await app.until(async()=>!!heldReply,10000,'user requested retry');
 check('An explicit retry clears the old capacity guidance while running',chatCalls===4&&await app.page(`return document.querySelector('#focus-next').textContent==='Watch bot'&&!document.querySelector('#work-focus [data-task-activity]').textContent.includes('Provider capacity reached')`));
 heldReply.setHeader('content-type','application/json');heldReply.end(JSON.stringify({message:{role:'assistant',content:'Fixture recovered reply; inspect before applying.'},done:true}));heldReply=null;
 await app.until(()=>app.page(`return document.querySelector('#focus-next').textContent==='Review the bot’s reply'`),10000,'recovered reply');
 check('Successful retry moves to review and leaves the task unaccepted',await app.page(`return window.cockpit.frame.projection.development_tasks[arguments[0]].status==='planned'&&document.querySelector('#work-focus [data-task-activity]').dataset.phase==='complete'`,[tasks[1].id]));
 await app.page(`document.querySelector('#toggle-schematics').click()`);await ready();

 }finally{if(heldReply){heldReply.statusCode=503;heldReply.end('{}');}providerFixture.close();}
 await app.page(`window.schematicNavigate('bots')`);await ready();await app.page(`document.querySelector('[data-schematic-node=request]').click()`);
 check('Bot schematic exposes request and reply internals',await app.page(`return !!document.querySelector('[data-schematic-node=request]')&&!!document.querySelector('[data-schematic-node=reply]')`));
 await shot('09_Bot_Internals');
 await app.page(`window.schematicNavigate('development-tasks')`);await ready();await app.page(`document.querySelector('[data-schematic-node=acceptance]').click()`);
 check('Review schematic separates applying files from acceptance',await app.page(`return !!document.querySelector('[data-schematic-node=apply]')&&document.querySelector('[data-schematic-node=acceptance] span').textContent==='Human decision required'`));
 await shot('10_Review_Internals');
 const server=createServer((req,res)=>res.end('<body style="background:red"><h1>Native preview fixture</h1></body>'));await new Promise(r=>server.listen(0,'127.0.0.1',r));
 try{
 await app.page(`document.querySelector('#toggle-schematics').click();window.schematicNavigate('browser');document.querySelector('#browser-url').value=arguments[0];document.querySelector('#browser-go').click()`,['http://127.0.0.1:'+server.address().port]);
 await app.until(async()=>((await app.native('browser_surface',{action:'status'})).tabs??[]).length>0,10000,'native preview');
 await app.page(`document.querySelector('#toggle-schematics').click()`);await ready();await new Promise(r=>setTimeout(r,500));
 execFileSync('/usr/bin/python3',['tools/development-capture-window.py',String(process.pid),`${out}/05_Browser_Cover.png`]);
 check('Browser schematic opens while the native preview remains retained',await app.page(`return !document.querySelector('#schematics').hidden && document.querySelector('#schematics h1').textContent.includes('Browser')`));
 await app.page(`document.querySelector('#toggle-schematics').click()`);
 check('Leaving the schematic restores the Browser page',await app.page(`return !document.querySelector('[data-screen=browser]').hidden`));
 await app.native('browser_surface',{action:'close'});
 }finally{server.close();}
 await app.page(`location.reload()`);await app.until(()=>app.page(`return !!document.querySelector('#work-focus [data-task-activity]')&&!!window.cockpit?.frame?.projection`),15000,'reloaded activity');
 check('Reload does not resurrect old output as a live request',await app.page(`return document.querySelector('#work-focus [data-task-activity]').dataset.phase==='none'&&document.querySelector('#work-focus .task-activity-output').hidden`));
 writeFileSync(`${out}/checks.json`,JSON.stringify({passed:true,checks},null,2));
}finally{if(app)await app.close();}
